import { createHash } from "node:crypto"
import { copyFileSync, existsSync, mkdirSync, renameSync, rmSync } from "node:fs"
import { dirname, resolve } from "node:path"

export interface UpdateManifest {version:string;channel:"stable"|"rc";minimumSchema:number;maximumSchema:number;sha256:string}
export function checkUpdate(input:{currentVersion:string;channel:"stable"|"rc";manifest:UpdateManifest;schemaVersion:number}){const compatible=input.schemaVersion>=input.manifest.minimumSchema&&input.schemaVersion<=input.manifest.maximumSchema,channelAllowed=input.channel==="rc"||input.manifest.channel==="stable",available=channelAllowed&&input.manifest.version!==input.currentVersion;return{schemaVersion:"mathos.update-check.v1",currentVersion:input.currentVersion,latestVersion:input.manifest.version,available,compatible,channel:input.channel}}
export function verifyUpdateArtifact(bytes:Uint8Array,expected:string){const actual=createHash("sha256").update(bytes).digest("hex");if(!/^[a-f0-9]{64}$/.test(expected)||actual!==expected)throw new Error("UPDATE_CHECKSUM_MISMATCH");return true}
export function applyAtomicUpdate(input:{current:string;candidate:string;preSmoke:(path:string)=>boolean;postSmoke:(path:string)=>boolean}){const current=resolve(input.current),candidate=resolve(input.candidate),backup=`${current}.previous`,staging=`${current}.staged-${process.pid}`;if(!existsSync(current)||!existsSync(candidate))throw new Error("UPDATE_ARTIFACT_MISSING");if(!input.preSmoke(candidate))throw new Error("UPDATE_PRE_SMOKE_FAILED");mkdirSync(dirname(current),{recursive:true});copyFileSync(candidate,staging);rmSync(backup,{force:true});renameSync(current,backup);try{renameSync(staging,current);if(!input.postSmoke(current))throw new Error("post smoke");return{applied:true,current,rollback:backup}}catch{rmSync(current,{force:true});renameSync(backup,current);rmSync(staging,{force:true});throw new Error("UPDATE_POST_SMOKE_FAILED_ROLLED_BACK")}}
export function rollbackUpdate(currentPath:string){const current=resolve(currentPath),backup=`${current}.previous`;if(!existsSync(backup))throw new Error("UPDATE_ROLLBACK_UNAVAILABLE");const failed=`${current}.failed-${Date.now()}`;renameSync(current,failed);try{renameSync(backup,current);rmSync(failed,{force:true});return{rolledBack:true,current}}catch(error){renameSync(failed,current);throw error}}
export function uninstallMathOS(input:{binary:string;productData:string;userData:string;workspaces:string[];purge:boolean}){rmSync(resolve(input.binary),{force:true});rmSync(resolve(input.productData),{recursive:true,force:true});if(input.purge){const user=resolve(input.userData);if(input.workspaces.some(path=>resolve(path)===user||resolve(path).startsWith(`${user}\\`)||resolve(path).startsWith(`${user}/`)))throw new Error("UNINSTALL_PURGE_CONTAINS_WORKSPACE");rmSync(user,{recursive:true,force:true})}return{removed:true,preservedWorkspaces:input.workspaces.map(path=>resolve(path)),preservedUserData:!input.purge}}
