import { ProcessSupervisor, type ProcessSupervisorOptions } from "./process-supervisor.ts"

interface Pending{resolve:(value:any)=>void;reject:(error:Error)=>void;timer:ReturnType<typeof setTimeout>;cleanup:()=>void}
/** onRequest answers requests the server sends to us (permission prompts, file reads); without it, or when it throws, the server gets "method not found" instead of waiting forever. */
export interface JsonRpcProcessOptions extends Omit<ProcessSupervisorOptions,"onLine"|"onError">{onNotification?:(method:string,params:unknown)=>void;onRequest?:(method:string,params:unknown)=>unknown;omitVersionHeader?:boolean}
export class JsonRpcProcess{
  private nextId=1;private readonly pending=new Map<number,Pending>();private readonly supervisor:ProcessSupervisor;private readonly onNotification?:JsonRpcProcessOptions["onNotification"];private readonly onRequest?:JsonRpcProcessOptions["onRequest"];private readonly omitVersionHeader:boolean;private fatalError:Error|null=null
  constructor(options:JsonRpcProcessOptions){this.onNotification=options.onNotification;this.onRequest=options.onRequest;this.omitVersionHeader=options.omitVersionHeader??false;const{omitVersionHeader:_,onNotification:__,onRequest:___,...supervisorOptions}=options;this.supervisor=new ProcessSupervisor({...supervisorOptions,onLine:line=>this.receive(line),onError:error=>this.failAll(error)});this.supervisor.onExit(code=>this.failAll(new Error(`EXTERNAL_PROCESS_EXITED: ${code}`)))}
  start():void{this.supervisor.start()}
  get pid(){return this.supervisor.pid}
  notify(method:string,params?:unknown):void{this.supervisor.writeLine({...this.header(),method,...(params===undefined?{}:{params})})}
  request<T=unknown>(method:string,params?:unknown,options:{timeoutMs?:number;signal?:AbortSignal}={}):Promise<T>{if(this.fatalError)return Promise.reject(this.fatalError);const id=this.nextId++;return new Promise<T>((resolve,reject)=>{let settled=false;const finish=()=>{if(settled)return false;settled=true;this.pending.delete(id);return true};const onAbort=()=>{if(!finish())return;clearTimeout(timer);this.notify("$/cancelRequest",{id});reject(new Error("JSONRPC_REQUEST_CANCELLED"))};const timer=setTimeout(()=>{if(!finish())return;options.signal?.removeEventListener("abort",onAbort);this.notify("$/cancelRequest",{id});reject(new Error("JSONRPC_REQUEST_TIMEOUT"))},options.timeoutMs??60_000);const cleanup=()=>options.signal?.removeEventListener("abort",onAbort);this.pending.set(id,{resolve:value=>{if(finish()){clearTimeout(timer);cleanup();resolve(value)}},reject:error=>{if(finish()){clearTimeout(timer);cleanup();reject(error)}},timer,cleanup});if(options.signal?.aborted)onAbort();else{options.signal?.addEventListener("abort",onAbort,{once:true});this.supervisor.writeLine({...this.header(),id,method,...(params===undefined?{}:{params})})}})}
  async stop():Promise<void>{this.failAll(new Error("EXTERNAL_PROCESS_STOPPED"));await this.supervisor.stop()}
  private receive(line:string):void{let message:any;try{message=JSON.parse(line)}catch{this.fatalError=new Error("JSONRPC_MALFORMED_FRAME");this.failAll(this.fatalError);return}if(!this.omitVersionHeader&&message?.jsonrpc!=="2.0")return;if(typeof message?.method==="string"){if(message.id===undefined||message.id===null)this.onNotification?.(message.method,message.params);else void this.answer(message.id,message.method,message.params);return}const id=typeof message?.id==="number"?message.id:null;if(id===null)return;const pending=this.pending.get(id);if(!pending)return;if(message.error)pending.reject(new Error(`JSONRPC_ERROR: ${message.error.code??"UNKNOWN"} ${message.error.message??""}`.trim()));else pending.resolve(message.result)}
  /** A server request carries its own id space; it must never be matched against our pending requests. */
  private async answer(id:string|number,method:string,params:unknown):Promise<void>{let reply:Record<string,unknown>;try{if(!this.onRequest)throw Object.assign(new Error(`Method not found: ${method}`),{code:-32601});const result=await this.onRequest(method,params);if(result===undefined)throw Object.assign(new Error(`Method not found: ${method}`),{code:-32601});reply={result}}catch(error){reply={error:{code:typeof(error as any)?.code==="number"?(error as any).code:-32603,message:error instanceof Error?error.message:String(error)}}}try{this.supervisor.writeLine({...this.header(),id,...reply})}catch{}}
  private header(){return this.omitVersionHeader?{}:{jsonrpc:"2.0"}}
  private failAll(error:Error):void{for(const item of this.pending.values()){clearTimeout(item.timer);item.cleanup();item.reject(error)}this.pending.clear()}
}
