import { buildExternalClientEnvironment } from "../auth/external-client-auth.ts"

export interface ProcessSupervisorOptions{executable:string;args?:string[];cwd?:string;env?:NodeJS.ProcessEnv;documentedAuthEnv?:string[];maxFrameBytes?:number;onLine?:(line:string)=>void;onStderr?:(line:string)=>void;onError?:(error:Error)=>void;platform?:NodeJS.Platform;treeKiller?:(pid:number,platform:NodeJS.Platform)=>Promise<void>}

export class ProcessSupervisor{
  private child:any=null;private stdoutTask:Promise<void>|null=null;private stderrTask:Promise<void>|null=null;private exitHandlers=new Set<(code:number)=>void>();readonly maxFrameBytes:number
  constructor(private readonly options:ProcessSupervisorOptions){const limit=options.maxFrameBytes??2_000_000;if(limit<1||limit>16_000_000)throw new Error("PROCESS_FRAME_LIMIT_INVALID");this.maxFrameBytes=limit}
  get pid():number|null{return this.child?.pid??null}
  start():void{if(this.child)throw new Error("PROCESS_ALREADY_STARTED");this.child=Bun.spawn([this.options.executable,...(this.options.args??[])],{cwd:this.options.cwd,env:buildExternalClientEnvironment(this.options.env,this.options.documentedAuthEnv),stdin:"pipe",stdout:"pipe",stderr:"pipe"});this.stdoutTask=this.consume(this.child.stdout,line=>this.options.onLine?.(line),true).catch(error=>{this.options.onError?.(error instanceof Error?error:new Error(String(error)));this.child?.kill?.()});this.stderrTask=this.consume(this.child.stderr,line=>this.options.onStderr?.(line),false);void this.child.exited.then((code:number)=>{for(const handler of this.exitHandlers)handler(code)})}
  onExit(handler:(code:number)=>void):()=>void{this.exitHandlers.add(handler);return()=>this.exitHandlers.delete(handler)}
  writeLine(value:unknown):void{if(!this.child?.stdin||typeof this.child.stdin==="number")throw new Error("PROCESS_NOT_RUNNING");const line=typeof value==="string"?value:JSON.stringify(value);if(Buffer.byteLength(line)>this.maxFrameBytes)throw new Error("PROCESS_FRAME_TOO_LARGE");this.child.stdin.write(`${line}\n`);this.child.stdin.flush?.()}
  async stop():Promise<void>{if(!this.child)return;const child=this.child,pid=child.pid;try{if(this.options.treeKiller)await this.options.treeKiller(pid,this.options.platform??process.platform);else await killProcessTree(pid,this.options.platform??process.platform)}finally{try{child.stdin?.end?.()}catch{}await Promise.race([child.exited,Bun.sleep(2_000).then(()=>child.kill?.("SIGKILL"))]);await Promise.allSettled([this.stdoutTask,this.stderrTask]);this.child=null}}
  private async consume(stream:ReadableStream<Uint8Array>,handler:(line:string)=>void,strict:boolean):Promise<void>{const reader=stream.getReader(),decoder=new TextDecoder();let buffered="";try{while(true){const{done,value}=await reader.read();if(done)break;buffered+=decoder.decode(value,{stream:true});if(Buffer.byteLength(buffered)>this.maxFrameBytes&&!buffered.includes("\n")){if(strict)throw new Error("PROCESS_FRAME_TOO_LARGE");buffered=""}let index:number;while((index=buffered.indexOf("\n"))>=0){const line=buffered.slice(0,index).replace(/\r$/,"");buffered=buffered.slice(index+1);if(Buffer.byteLength(line)>this.maxFrameBytes){if(strict)throw new Error("PROCESS_FRAME_TOO_LARGE");continue}if(line)handler(line)}}if(buffered&&Buffer.byteLength(buffered)<=this.maxFrameBytes)handler(buffered)}finally{reader.releaseLock()}}
}

export async function killProcessTree(pid:number,platform:NodeJS.Platform=process.platform):Promise<void>{if(platform==="win32"){const result=Bun.spawn(["taskkill","/PID",String(pid),"/T","/F"],{stdin:"ignore",stdout:"ignore",stderr:"ignore"});await result.exited;return}try{process.kill(-pid,"SIGTERM")}catch{try{process.kill(pid,"SIGTERM")}catch{}}}
