import { createHash } from "node:crypto"
import { ALLOWED_LOCAL_STATUSES,type PremiseCandidate,type PremiseRetrievalResult,type PremiseRole,type PremiseSetCandidate } from "./types.ts"
export const DEFAULT_PREMISE_SET_SIZE=8,MAX_PREMISE_SET_SIZE=20
const tokens=(candidate:PremiseCandidate)=>new Set([...(candidate.generation?.matchedTokens??[]),...candidate.reasons,...(candidate.profile?.constants??[]),...(candidate.profile?.typeConstructors??[])].map((value)=>value.toLowerCase()))
const role=(candidate:PremiseCandidate):PremiseRole=>{const text=[...tokens(candidate)].join(" ");if(/conclusion|target/.test(text))return"CONCLUSION_MATCH";if(/rewrite|simp|equality/.test(text))return"REWRITE";if(/type|structure|instance/.test(text))return"TYPECLASS_OR_STRUCTURE";if(/domain|local/.test(text))return"DOMAIN_LEMMA";if(/bridge|implication/.test(text))return"BRIDGE_LEMMA";return"AUXILIARY"}
const allowed=(candidate:PremiseCandidate)=>candidate.declaration.origin!=="workspace"||(ALLOWED_LOCAL_STATUSES as readonly string[]).includes(candidate.declaration.claimStatus??"")
export class GlobalPremiseSetPlanner{
  plan(result:PremiseRetrievalResult,options:{maxSize?:number;dependencyNames?:string[];graphHints?:string[]}={}):PremiseSetCandidate{
    const limit=Math.min(MAX_PREMISE_SET_SIZE,Math.max(1,options.maxSize??DEFAULT_PREMISE_SET_SIZE)),ranked=result.candidates.filter(allowed).sort((a,b)=>b.score-a.score||a.declaration.name.localeCompare(b.declaration.name)),goalFeatures=new Set<string>()
    if(result.goalProfile?.known)for(const value of [...result.goalProfile.constants,...result.goalProfile.typeConstructors,...result.goalProfile.conclusionTokens,...(options.dependencyNames??[]),...(options.graphHints??[])])if(value)goalFeatures.add(value.toLowerCase())
    const selected:Array<{candidate:PremiseCandidate;marginal:number}>=[],covered=new Set<string>();let redundancyPenalty=0
    while(selected.length<limit&&ranked.length){let bestIndex=0,bestValue=-Infinity,bestMarginal=0,bestRedundancy=0
      for(let index=0;index<ranked.length;index++){const candidate=ranked[index]!,features=tokens(candidate),marginal=[...features].filter((feature)=>!covered.has(feature)&&(goalFeatures.size===0||goalFeatures.has(feature))).length,redundancy=selected.reduce((sum,item)=>{const other=tokens(item.candidate),intersection=[...features].filter((feature)=>other.has(feature)).length;return sum+intersection/Math.max(1,Math.min(features.size,other.size))},0),value=candidate.score+marginal*4-redundancy*5;if(value>bestValue||(value===bestValue&&candidate.declaration.name.localeCompare(ranked[bestIndex]!.declaration.name)<0)){bestIndex=index;bestValue=value;bestMarginal=marginal;bestRedundancy=redundancy}}
      const candidate=ranked.splice(bestIndex,1)[0]!;selected.push({candidate,marginal:bestMarginal});for(const feature of tokens(candidate))if(goalFeatures.size===0||goalFeatures.has(feature))covered.add(feature);redundancyPenalty+=bestRedundancy
    }
    const members=selected.map(({candidate,marginal})=>({declarationName:candidate.declaration.name,role:role(candidate),sourceRank:result.candidates.findIndex((item)=>item.declaration.name===candidate.declaration.name)+1,marginalCoverage:marginal,provenance:{indexRevision:result.indexRevision,retrievalMode:result.mode,channels:[...(candidate.generation?.channels??[])].sort()}})),names=members.map((member)=>member.declarationName),id=`GPS-${createHash("sha256").update(JSON.stringify({indexRevision:result.indexRevision,mode:result.mode,names})).digest("hex").slice(0,16)}`
    return{id,members,setScore:Number((selected.reduce((sum,item)=>sum+item.candidate.score,0)+covered.size-redundancyPenalty).toFixed(6)),goalCoverage:[...covered].sort(),redundancyPenalty:Number(redundancyPenalty.toFixed(6)),unresolvedGoalFeatures:result.goalProfile?.known?[...goalFeatures].filter((feature)=>!covered.has(feature)).sort():["UNKNOWN_GOAL_PROFILE"],generationVersion:"global-premise-set-v1"}
  }
}
export interface PremiseSetBenchmarkMetrics{kernelAcceptedRate:number;proofCompileRate:number;p95LatencyMs:number}
export function evaluateGlobalPremisePromotion(input:{baseline:PremiseSetBenchmarkMetrics;candidate:PremiseSetBenchmarkMetrics;completeRegressions:number;latencyBudgetMs:number}):"PROMOTE"|"REJECT"|"INCONCLUSIVE"{if(input.completeRegressions>0||input.candidate.kernelAcceptedRate<input.baseline.kernelAcceptedRate||input.candidate.proofCompileRate<input.baseline.proofCompileRate||input.candidate.p95LatencyMs>input.latencyBudgetMs)return"REJECT";if(!Number.isFinite(input.candidate.kernelAcceptedRate)||!Number.isFinite(input.candidate.proofCompileRate)||input.baseline.kernelAcceptedRate+input.baseline.proofCompileRate+input.candidate.kernelAcceptedRate+input.candidate.proofCompileRate===0)return"INCONCLUSIVE";return"PROMOTE"}
