import type { SolverPolicySnapshot,SolverTrustClass } from "@mathos/domain"
import type { SolverJobRepository,SolverResultRepository } from "@mathos/storage"
import type { ArtifactStorePort } from "../ports/artifact-store-port.ts"
import { validateSolverResult } from "@mathos/solvers"
import type { SolverAdapterRegistry } from "./solver-registry.ts"
type Row={id:string;[key:string]:unknown}
export interface SolverLabDependencies{registry:SolverAdapterRegistry;jobs:SolverJobRepository;results:SolverResultRepository;artifacts:ArtifactStorePort;unitOfWork<T>(work:()=>T):T;now():string;nextId(prefix:string):string;validateWitness(witness:unknown,payload:Record<string,unknown>):boolean;validateCertificate(certificate:unknown,payload:Record<string,unknown>):boolean;leanReplay(result:Row):Promise<{passed:boolean;inputHash:string;outputHash:string}>;createEvidence(result:Row):string}
export interface SolverLabRunInput{id:string;workspaceId:string;branchId:string;claimId:string|null;solverId:string;problemKind:string;payload:Record<string,unknown>;policy:SolverPolicySnapshot}
export class SolverLabService{constructor(private readonly d:SolverLabDependencies){}
  async run(input:SolverLabRunInput):Promise<{job:Row;result:Row}>{const adapter=this.d.registry.get(input.solverId);if(!adapter||adapter.descriptor.health!=="READY"||!adapter.descriptor.problemKinds.includes(input.problemKind))throw new Error(`SOLVER_UNAVAILABLE:${input.solverId}`);const now=this.d.now(),request=JSON.stringify({schemaVersion:"mathos.solver-request.v1",problemKind:input.problemKind,payload:input.payload}),requestArtifactId=this.d.artifacts.put(`solver/${input.id}/request.json`,new TextEncoder().encode(request));this.d.jobs.insert({id:input.id,workspaceId:input.workspaceId,branchId:input.branchId,claimId:input.claimId,solverId:input.solverId,solverVersion:adapter.descriptor.version,problemKind:input.problemKind,requestArtifactId,status:"RUNNING",policySnapshot:input.policy,revision:1,createdAt:now,startedAt:now,finishedAt:null});const raw=await adapter.solve({problemKind:input.problemKind,payload:input.payload,timeoutMs:input.policy.timeoutMs});const witnessValid=raw.outcome==="COUNTEREXAMPLE"?this.d.validateWitness(raw.witness,input.payload):false,certificateValid=raw.certificate!==undefined?this.d.validateCertificate(raw.certificate,input.payload):false;let requested=(raw.trustClass??"UNTRUSTED") as SolverTrustClass;if(witnessValid)requested="WITNESS_CHECKED";if(certificateValid)requested="CERTIFICATE_CHECKED";const validated=validateSolverResult({...raw,trustClass:requested},{witnessValid,certificateValid});const errorCode=raw.outcome==="COUNTEREXAMPLE"&&!witnessValid?"INVALID_COUNTEREXAMPLE":raw.errorCode??null,status=errorCode==="SOLVER_TIMEOUT"?"TIMED_OUT":validated.outcome==="ERROR"||errorCode?"FAILED":"SUCCEEDED",id=this.d.nextId("SR");const witnessArtifactId=raw.witness===undefined?null:this.d.artifacts.put(`solver/${input.id}/${id}-witness.json`,new TextEncoder().encode(JSON.stringify(raw.witness))),certificateArtifactId=raw.certificate===undefined?null:this.d.artifacts.put(`solver/${input.id}/${id}-certificate.txt`,new TextEncoder().encode(String(raw.certificate)));let result:Row={id,jobId:input.id,outcome:validated.outcome,trustClass:validated.trustClass,structured:{...(validated.structured??{}),errorCode,diagnostics:validated.diagnostics},witnessArtifactId,certificateArtifactId,replayStatus:"NOT_RUN",exact:raw.exact===true,deterministic:true,runtimeFingerprint:`${adapter.descriptor.id}@${adapter.descriptor.version}`,inputHash:String(raw.inputHash??""),outputHash:String(raw.outputHash??""),evidenceId:null,createdAt:now};this.d.unitOfWork(()=>{result.evidenceId=this.d.createEvidence(result);this.d.results.insert(result);this.d.jobs.updateExpectedRevision(input.id,1,{status,finishedAt:now})});return{job:this.d.jobs.get(input.id)!,result:this.d.results.get(id)!}}
  async replay(resultId:string):Promise<Row>{const source=this.d.results.get(resultId);if(!source)throw new Error(`SOLVER_RESULT_NOT_FOUND:${resultId}`);const replay=await this.d.leanReplay(source),matches=replay.inputHash===source.inputHash&&replay.outputHash===source.outputHash,trustClass:SolverTrustClass=source.trustClass==="CERTIFICATE_CHECKED"&&replay.passed&&matches?"LEAN_REPLAYED":source.trustClass as SolverTrustClass,replayStatus=replay.passed?(matches?"PASS":"HASH_MISMATCH"):"FAIL",evidenceId=this.d.createEvidence({...source,trustClass,replayStatus});return this.d.results.recordReplay(source.id,String(source.inputHash),String(source.outputHash),{trustClass,replayStatus,evidenceId})}
}
