import type{ModelCapabilities,ModelProvider,ModelRequest,ModelResponse,StructuredModelRequest}from"../types.ts";import{AcpClient}from"../transports/acp-client.ts";import{extractJson}from"../json.ts";import{InvalidStructuredResponse}from"../errors.ts"
export function discoverGeminiExecutable(override?:string,which:(name:string)=>string|null=name=>Bun.which(name)){return override??which(process.platform==="win32"?"gemini.cmd":"gemini")??which("gemini")}
export interface AcpProviderOptions{args?:string[];env?:NodeJS.ProcessEnv;timeoutMs?:number}
/** One ACP session per request: the agent keeps history inside a session, while MathOS sends the whole transcript each time. */
export class AcpSessionProvider{
 private readonly client:AcpClient;private sessionId:string|null=null;private connected=false
 constructor(executable:string,options:AcpProviderOptions,private readonly label:string){const[command,...prefix]=acpCommand(executable);this.client=new AcpClient({executable:command!,args:[...prefix,...(options.args??["--acp"])],env:options.env});this.timeoutMs=options.timeoutMs}
 private readonly timeoutMs:number|undefined
 async connect(check?:(initialized:any)=>void){this.client.start();const initialized:any=await this.client.initialize({name:"MathOS",version:"1.0"});check?.(initialized);this.sessionId=(await this.client.newSession()).sessionId;this.connected=true;return initialized}
 async prompt(request:ModelRequest){if(!this.connected)throw new Error(`${this.label}_NOT_CONNECTED`);const sessionId=this.sessionId??(await this.client.newSession()).sessionId;this.sessionId=null;const result=await this.client.prompt(sessionId,request.messages.map(message=>`${message.role}: ${message.content}`).join("\n"),{signal:request.signal,timeoutMs:this.timeoutMs,...(request.onDelta?{onDelta:request.onDelta}:{})});if(!result.text)throw new Error(result.stopReason==="refusal"?`${this.label}_REFUSED`:`${this.label}_RESPONSE_EMPTY`);return result}
 async close(){this.connected=false;this.sessionId=null;await this.client.stop()}
}
/** npm installs `.cmd` shims on Windows; those only start through cmd.exe. */
export function acpCommand(executable:string,platform:NodeJS.Platform=process.platform):string[]{return platform==="win32"&&/\.(cmd|bat)$/i.test(executable)?["cmd.exe","/d","/s","/c",executable]:[executable]}
export class GeminiCliEnterpriseProvider implements ModelProvider{readonly id="gemini-cli-enterprise";readonly capabilities:ModelCapabilities={structuredOutput:false,toolCalling:false,reasoning:true,streaming:true,vision:false};private readonly session:AcpSessionProvider;constructor(readonly model:string,executable:string,options:AcpProviderOptions|string[]={}){this.session=new AcpSessionProvider(executable,Array.isArray(options)?{args:options}:options,"GEMINI_CLI")}connect(){return this.session.connect()}async generate(request:ModelRequest):Promise<ModelResponse>{const result=await this.session.prompt(request);return{text:result.text,provider:this.id,model:this.model,...(result.reasoning?{reasoning:result.reasoning}:{})}}async generateStructured<T>(request:StructuredModelRequest<T>){const response=await this.generate(request);try{return request.parse(extractJson(response.text))}catch{throw new InvalidStructuredResponse("Gemini CLI returned invalid structured output.")}}close(){return this.session.close()}}
