import { afterEach, describe, expect, test } from "bun:test"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { AlignmentFindingRepository, DatabaseClient, FormalAlignmentRepository, StatementRevisionRepository } from "@mathos/storage"
import { AlignmentService } from "@mathos/core"

const clients:DatabaseClient[]=[]
async function setup(severity:"INFO"|"ERROR"="INFO"){const client=new DatabaseClient(join(tmpdir(),`mathos-approval-${crypto.randomUUID()}.sqlite`));client.migrate();clients.push(client);const revisions=new StatementRevisionRepository(client.db),alignments=new FormalAlignmentRepository(client.db),findings=new AlignmentFindingRepository(client.db);revisions.insert({id:"N-1",claimId:"C-1",kind:"NATURAL",sourceEntityId:"C-1",text:"N",contextRevisionId:"CR-1",revision:1,contentHash:"nh",createdBy:"user",createdAt:"now"});revisions.insert({id:"F-1",claimId:"C-1",kind:"FORMAL",sourceEntityId:"FS-1",text:"F",contextRevisionId:"CR-1",revision:1,contentHash:"fh",createdBy:"model",createdAt:"now"});let id=0;const events:string[]=[];const service=new AlignmentService({revisions,alignments,findings,clock:{now:()=>"2030"},nextId:(p)=>`${p}-${++id}`,writeEvent:(type)=>events.push(type),auditor:{id:"a",model:"m",audit:async()=>({verdict:severity==="ERROR"?"MISMATCH":"MATCH",backTranslation:"",symbolMapping:[],findings:[{dimension:"CONCLUSION",severity,naturalFragment:"",formalFragment:"",message:"finding",resolutionStatus:"OPEN",reviewerNote:null}]})}});const run=await service.run({claimId:"C-1",naturalRevisionId:"N-1",formalRevisionId:"F-1",contextRevisionId:"CR-1"});return{service,revisions,run,events}}
afterEach(()=>{while(clients.length)clients.pop()!.close()})
describe("alignment human approval",()=>{
  test("binds approval to exact hashes and human actor",async()=>{const{service,run,events}=await setup();const approved=service.approve(run.alignment.id,{actorId:"reviewer-1",actorType:"human",naturalHash:"nh",formalHash:"fh",contextRevisionId:"CR-1"});expect(approved.status).toBe("HUMAN_APPROVED");expect(events).toContain("alignment.human-approved")})
  test("rejects hash/context mismatch, model actors and unresolved errors",async()=>{const a=await setup();expect(()=>a.service.approve(a.run.alignment.id,{actorId:"model",actorType:"model",naturalHash:"nh",formalHash:"fh",contextRevisionId:"CR-1"})).toThrow("HUMAN_ACTOR_REQUIRED");expect(()=>a.service.approve(a.run.alignment.id,{actorId:"h",actorType:"human",naturalHash:"wrong",formalHash:"fh",contextRevisionId:"CR-1"})).toThrow("ALIGNMENT_REVISION_MISMATCH");const b=await setup("ERROR");expect(()=>b.service.approve(b.run.alignment.id,{actorId:"h",actorType:"human",naturalHash:"nh",formalHash:"fh",contextRevisionId:"CR-1"})).toThrow("UNRESOLVED_ALIGNMENT_ERROR")})
  test("revision change invalidates previous approval",async()=>{const{service,revisions,run}=await setup();service.approve(run.alignment.id,{actorId:"h",actorType:"human",naturalHash:"nh",formalHash:"fh",contextRevisionId:"CR-1"});revisions.insert({id:"N-2",claimId:"C-1",kind:"NATURAL",sourceEntityId:"C-1",text:"changed",contextRevisionId:"CR-1",revision:2,contentHash:"nh2",createdBy:"user",createdAt:"later"});expect(service.currentApproval("C-1")).toBeNull()})
})
