import{describe,expect,test}from"bun:test";import{CodexAppServerClient,OpenAICodexAccountProvider,discoverCodexExecutable,probeCodexVersion,validateCodexSchema,CODEX_REQUIRED_METHODS}from"@mathos/models";import{resolve}from"node:path"
const fixture=resolve(import.meta.dir,"fixtures/codex-app-server/fake.ts"),schema={methods:CODEX_REQUIRED_METHODS.map(name=>({name}))}
describe("Codex app-server account provider",()=>{
 test("discovers explicit, macOS PATH and Windows .exe clients and parses version",async()=>{const seen:string[]=[];const runtime={which:(name:string)=>{seen.push(name);return name==="codex.exe"?"C:/Codex/codex.exe":name==="codex"?"/usr/local/bin/codex":null},run:async()=>({exitCode:0,stdout:"codex-cli 1.2.3"})};expect(discoverCodexExecutable({override:"/custom/codex",runtime})).toBe("/custom/codex");expect(discoverCodexExecutable({platform:"win32",runtime})).toBe("C:/Codex/codex.exe");expect(discoverCodexExecutable({platform:"darwin",runtime})).toBe("/usr/local/bin/codex");expect((await probeCodexVersion("codex",runtime)).version).toBe("1.2.3");expect(seen).toContain("codex.exe")})
 test("fails closed when generated schema lacks a required method",()=>{expect(()=>validateCodexSchema({methods:[{name:"initialize"}]})).toThrow("CODEX_SCHEMA_METHOD_MISSING")})
 test("accepts the current Codex v2 schema bundle method enums",()=>{const schema={definitions:{ServerRequest:{oneOf:CODEX_REQUIRED_METHODS.map(name=>({properties:{method:{enum:[name]}}}))}}};expect(validateCodexSchema(schema)).toBe(true)})
 test("sends the truthful MathOS client identity during initialize",async()=>{const client=new CodexAppServerClient(process.execPath,[fixture],{schema,version:"1.0.0-rc.1"});client.start();try{const result:any=await client.initialize();expect(result.received.clientInfo).toEqual({name:"mathos_model_bridge",title:"MathOS Model Provider Bridge",version:"1.0.0-rc.1"})}finally{await client.stop()}})
 test("initializes truthfully, reads account, handles login, inference and explicit logout",async()=>{const provider=new OpenAICodexAccountProvider("codex-test",{executable:process.execPath,args:[fixture],schema,version:"1.0.0-rc.1"});try{expect(await provider.connect()).toEqual({account:{type:"chatgpt",planType:"pro"}});const login=await provider.login("chatgptDeviceCode");expect(login).toEqual({type:"chatgptDeviceCode",deviceCode:"ephemeral-device-code"});expect(JSON.stringify(provider)).not.toContain("ephemeral-device-code");expect((await provider.generate({messages:[{role:"user",content:"solve"}]})).text).toBe("answer");expect(await provider.models()).toEqual({data:[{id:"codex-test"}]});expect(await provider.rateLimits()).toEqual({remaining:null});expect(()=>provider.logout()).toThrow("CODEX_LOGOUT_CONFIRMATION_REQUIRED");await provider.logout(true)}finally{await provider.close()}})
 test("fails provider calls when app-server requests shell or tools",async()=>{const provider=new OpenAICodexAccountProvider("tool-model",{executable:process.execPath,args:[fixture],schema,version:"1.0.0"});try{await provider.connect();let error:unknown;try{await provider.generate({messages:[{role:"user",content:"unsafe"}]})}catch(caught){error=caught}expect(error).toBeInstanceOf(Error);expect((error as Error).message).toBe("CODEX_TOOL_REQUEST_FORBIDDEN")}finally{await provider.close()}})
})
