import{describe,expect,test}from"bun:test";import{GitHubCopilotProvider,copilotCliPath,createOfficialCopilotAdapter,normalizeCopilotError,type CopilotSdkAdapter,type CopilotSdkSession}from"@mathos/models"
class FakeAdapter implements CopilotSdkAdapter{started=false;stopped=false;config:Record<string,unknown>|null=null;subscriptionError=false;async start(){if(this.subscriptionError)throw new Error("Copilot subscription entitlement missing");this.started=true}async stop(){this.stopped=true}async listModels(){return[{id:"gpt-test",name:"GPT Test",capabilities:{supports:{reasoningEffort:true}},billing:{multiplier:1}}]}async createSession(config:Record<string,unknown>):Promise<CopilotSdkSession>{this.config=config;return{sendAndWait:async()=>({data:{content:"answer",usage:{input_tokens:5,output_tokens:2}}}),disconnect:async()=>{}}}}
describe("GitHub Copilot provider",()=>{
 test("uses logged-in SDK adapter, normalizes models and disables tools and MCP",async()=>{const adapter=new FakeAdapter(),provider=new GitHubCopilotProvider("gpt-test",adapter);await provider.start();expect(adapter.started).toBe(true);expect(await provider.models()).toEqual([{id:"gpt-test",name:"GPT Test",capabilities:{supports:{reasoningEffort:true}},billing:{multiplier:1}}]);const response=await provider.generate({messages:[{role:"user",content:"solve"}]});expect(response).toEqual({text:"answer",provider:"github-copilot-account",model:"gpt-test",usage:{inputTokens:5,outputTokens:2}});expect(adapter.config).toEqual(expect.objectContaining({clientName:"MathOS",model:"gpt-test",availableTools:[],excludedTools:["*"],mcpServers:{},customAgents:[],skillDirectories:[]}));expect(JSON.stringify(adapter.config)).not.toMatch(/clientSecret|githubToken/i);await provider.stop();expect(adapter.stopped).toBe(true)})
 test("returns typed error when logged-in user has no Copilot subscription",async()=>{const adapter=new FakeAdapter();adapter.subscriptionError=true;await expect(new GitHubCopilotProvider("gpt-test",adapter).start()).rejects.toThrow("COPILOT_SUBSCRIPTION_REQUIRED")})
 test("model routes start and stop the Copilot runtime through connect and close",async()=>{const adapter=new FakeAdapter(),provider=new GitHubCopilotProvider("gpt-test",adapter);await provider.connect();expect(adapter.started).toBe(true);await provider.close();expect(adapter.stopped).toBe(true)})
 test("an unauthenticated Copilot runtime asks for sign-in",()=>{expect(normalizeCopilotError(new Error("Request models.list failed with message: Not authenticated. Please authenticate first.")).message).toBe("COPILOT_LOGIN_REQUIRED")})
 test("the official adapter sets the Copilot home empty mode requires and falls back to the signed-in CLI",()=>{expect(()=>createOfficialCopilotAdapter({cliPath:process.execPath,env:{HOME:"/tmp/mathos-copilot-home"}})).not.toThrow();expect(copilotCliPath("C:/Users/u/AppData/Roaming/npm/copilot.cmd","linux")).toBe("C:/Users/u/AppData/Roaming/npm/copilot.cmd")})
})
