import{describe,expect,test}from"bun:test";import{EnvironmentSecretStore,MODEL_PROFILE_V2_SCHEMA,createDirectProvider,discoverOpenRouterModels,type ModelProfileV2}from"@mathos/models"
function profile(descriptorId:string,overrides:Partial<ModelProfileV2>={}):ModelProfileV2{return{schemaVersion:MODEL_PROFILE_V2_SCHEMA,id:"profile",descriptorId,displayName:"Profile",model:"test-model",endpointPresetId:null,baseUrlOverride:null,auth:{kind:"secret-ref",secretRef:"model.profile"},enabled:true,timeoutMs:1000,maxResponseBytes:10000,maxOutputTokens:null,reasoningEffort:null,allowedRoles:["primary"],requestConcurrency:1,metadata:{createdAt:"2026-09-02T00:00:00Z",updatedAt:"2026-09-02T00:00:00Z",migratedFromV1:false},...overrides}}
const secrets=new EnvironmentSecretStore({MATHOS_SECRET_MODEL_PROFILE:"test-secret"})
describe("direct provider factory",()=>{
 test("prefers Responses for OpenAI and allows explicit Chat",async()=>{const paths:string[]=[];const fetchImpl=(async input=>{const path=new URL(String(input)).pathname;paths.push(path);return path.endsWith("/responses")?Response.json({output_text:"ok"}):Response.json({choices:[{message:{content:"ok"}}]})}) as typeof fetch;const responses=await createDirectProvider(profile("openai-api"),{secrets,fetch:fetchImpl});await responses.generate({messages:[{role:"user",content:"hi"}]});const chat=await createDirectProvider(profile("openai-api",{endpointPresetId:"chat"}),{secrets,fetch:fetchImpl});await chat.generate({messages:[{role:"user",content:"hi"}]});expect(paths).toEqual(["/v1/responses","/v1/chat/completions"])})
 test("maps Anthropic, Gemini and preset protocols",async()=>{const paths:string[]=[];const fetchImpl=(async input=>{const path=new URL(String(input)).pathname;paths.push(path);return path.endsWith("/messages")?Response.json({content:[{type:"text",text:"ok"}]}):Response.json({choices:[{message:{content:"ok"}}]})}) as typeof fetch;for(const id of["anthropic-api","gemini-api"]){const provider=await createDirectProvider(profile(id),{secrets,fetch:fetchImpl});await provider.generate({messages:[{role:"user",content:"hi"}]})}expect(paths).toEqual(["/v1/messages","/v1beta/openai/chat/completions"])})
 test("requires generic endpoint and protocol, and gates live PAYG usage",async()=>{await expect(createDirectProvider(profile("generic-openai-compatible"),{secrets})).rejects.toThrow("PROVIDER_ENDPOINT_REQUIRED");await expect(createDirectProvider(profile("generic-openai-compatible",{baseUrlOverride:"https://example.test/v1"}),{secrets})).rejects.toThrow("GENERIC_PROTOCOL_REQUIRED");await expect(createDirectProvider(profile("openai-api"),{secrets,live:true})).rejects.toThrow("LIVE_USAGE_ACCEPTANCE_REQUIRED")})
 test("uses truthful OpenRouter app identity headers for calls and discovery",async()=>{const seen:Array<Record<string,string|null>>=[];const fetchImpl=(async(_input,init)=>{const headers=new Headers(init?.headers);seen.push({referer:headers.get("HTTP-Referer"),title:headers.get("X-Title")});return Response.json({data:[]})}) as typeof fetch;await discoverOpenRouterModels("https://openrouter.ai/api/v1","secret",fetchImpl);const provider=await createDirectProvider(profile("openrouter"),{secrets,fetch:(async(_input,init)=>{const headers=new Headers(init?.headers);seen.push({referer:headers.get("HTTP-Referer"),title:headers.get("X-Title")});return Response.json({choices:[{message:{content:"ok"}}]})}) as typeof fetch});await provider.generate({messages:[{role:"user",content:"hi"}]});expect(seen).toEqual([{referer:"https://github.com/bakiacikgoz/MathOS",title:"MathOS"},{referer:"https://github.com/bakiacikgoz/MathOS",title:"MathOS"}])})
})
