import { describe,expect,test } from "bun:test"
import { JsonRpcProcess, ProcessSupervisor, buildExternalClientEnvironment } from "@mathos/models"
import { resolve } from "node:path"
const fixture=resolve(import.meta.dir,"fixtures/provider-process/fake-jsonrpc.ts")

describe("safe external process transport",()=>{
  test("round trips JSON-RPC with monotonic ids and allowlisted environment",async()=>{const rpc=new JsonRpcProcess({executable:process.execPath,args:[fixture],env:{PATH:process.env.PATH,ALLOWED_TOKEN:"owned",NODE_OPTIONS:"--inspect",UNRELATED:"drop"},documentedAuthEnv:["ALLOWED_TOKEN"]});rpc.start();try{expect(await rpc.request<any>("first",{n:1})).toEqual({method:"first",params:{n:1}});expect(await rpc.request<any>("second")).toEqual({method:"second",params:null})}finally{await rpc.stop()}const env=buildExternalClientEnvironment({PATH:"/bin",ALLOWED_TOKEN:"owned",NODE_OPTIONS:"bad",LD_PRELOAD:"bad",UNRELATED:"bad"},["ALLOWED_TOKEN"]);expect(env).toEqual({PATH:"/bin",ALLOWED_TOKEN:"owned"})})
  test("handles timeout, cancellation and crash",async()=>{const rpc=new JsonRpcProcess({executable:process.execPath,args:[fixture]});rpc.start();try{await expect(rpc.request("hang",{}, {timeoutMs:10})).rejects.toThrow("JSONRPC_REQUEST_TIMEOUT");const controller=new AbortController(),pending=rpc.request("hang",{}, {signal:controller.signal});controller.abort();await expect(pending).rejects.toThrow("JSONRPC_REQUEST_CANCELLED");await expect(rpc.request("crash")).rejects.toThrow("EXTERNAL_PROCESS_EXITED: 7")}finally{await rpc.stop()}})
  test("rejects oversized frames and abstracts process-tree shutdown",async()=>{expect(()=>new ProcessSupervisor({executable:process.execPath,maxFrameBytes:16_000_001})).toThrow("PROCESS_FRAME_LIMIT_INVALID");const calls:Array<[number,NodeJS.Platform]>=[];const supervisor=new ProcessSupervisor({executable:process.execPath,args:[fixture],platform:"win32",treeKiller:async(pid,platform)=>{calls.push([pid,platform]);try{process.kill(pid,"SIGTERM")}catch{}}});supervisor.start();await supervisor.stop();expect(calls[0]?.[1]).toBe("win32")})
  test("bounds stdout frames and captures stderr separately",async()=>{const stderr:string[]=[];const rpc=new JsonRpcProcess({executable:process.execPath,args:[fixture],maxFrameBytes:100,onStderr:line=>stderr.push(line)});rpc.start();try{expect(await rpc.request<any>("stderr")).toEqual({method:"stderr",params:null});await Bun.sleep(10);expect(stderr).toEqual(["fixture-stderr"]);await expect(rpc.request("oversize")).rejects.toThrow("PROCESS_FRAME_TOO_LARGE")}finally{await rpc.stop()}})
})
