import { describe,expect,test } from "bun:test"
import { GlobalPremiseSetPlanner,evaluateGlobalPremisePromotion } from "@mathos/retrieval"
import type { PremiseRetrievalResult,PremiseCandidate } from "@mathos/retrieval"
const candidate=(name:string,score:number,reasons:string[],extra:Partial<PremiseCandidate>={}):PremiseCandidate=>({declaration:{name,kind:"theorem",signature:name,origin:"mathlib"},score,reasons,generation:{channels:reasons,matchedTokens:reasons},...extra})
const result=(candidates:PremiseCandidate[],known=true):PremiseRetrievalResult=>({candidates,indexRevision:"IDX-1",query:"goal",localCount:0,mathlibCount:candidates.length,mode:"FORMAL_GOAL",goalProfile:{rawTarget:"A → B",constants:["A","B"],namespaces:[],typeConstructors:[],operators:[],localTypes:[],conclusionTokens:["B"],isEquality:false,isIff:false,isImplication:true,isExistential:false,isUniversal:false,known}})
describe("global premise set",()=>{
  test("selects complementary roles and penalizes redundant theorems",()=>{const planner=new GlobalPremiseSetPlanner();const set=planner.plan(result([candidate("conclusion",10,["conclusion"]),candidate("rewriteA",9,["rewrite","A"]),candidate("rewriteDuplicate",8.9,["rewrite","A"]),candidate("bridge",8,["bridge","B"])]),{maxSize:3});expect(set.members.map((member)=>member.declarationName)).toEqual(["rewriteA","bridge","conclusion"]);expect(new Set(set.members.map((member)=>member.role)).size).toBeGreaterThan(1);expect(set.redundancyPenalty).toBeGreaterThanOrEqual(0)})
  test("is deterministic, unique and hard-bounded",()=>{const candidates=Array.from({length:30},(_,index)=>candidate(`T${index}`,30-index,[`f${index}`]));const planner=new GlobalPremiseSetPlanner();const a=planner.plan(result(candidates),{maxSize:99}),b=planner.plan(result([...candidates].reverse()),{maxSize:99});expect(a.id).toBe(b.id);expect(a.members.map((m)=>m.declarationName)).toEqual(b.members.map((m)=>m.declarationName));expect(a.members).toHaveLength(20);expect(new Set(a.members.map((m)=>m.declarationName)).size).toBe(20)})
  test("excludes forbidden local statuses and falls back for unknown goals",()=>{const local=candidate("Local.bad",100,["best"],{declaration:{name:"Local.bad",kind:"theorem",signature:"x",origin:"workspace",claimStatus:"CONJECTURE"}}),safe=candidate("Safe",1,[]);const set=new GlobalPremiseSetPlanner().plan(result([local,safe],false));expect(set.members.map((m)=>m.declarationName)).toEqual(["Safe"]);expect(set.unresolvedGoalFeatures).toContain("UNKNOWN_GOAL_PROFILE")})
  test("promotion gate rejects proof regressions and latency excess",()=>{expect(evaluateGlobalPremisePromotion({baseline:{kernelAcceptedRate:.5,proofCompileRate:.6,p95LatencyMs:100},candidate:{kernelAcceptedRate:.4,proofCompileRate:.7,p95LatencyMs:90},completeRegressions:0,latencyBudgetMs:200})).toBe("REJECT");expect(evaluateGlobalPremisePromotion({baseline:{kernelAcceptedRate:.5,proofCompileRate:.6,p95LatencyMs:100},candidate:{kernelAcceptedRate:.5,proofCompileRate:.6,p95LatencyMs:250},completeRegressions:0,latencyBudgetMs:200})).toBe("REJECT");expect(evaluateGlobalPremisePromotion({baseline:{kernelAcceptedRate:.5,proofCompileRate:.6,p95LatencyMs:100},candidate:{kernelAcceptedRate:.5,proofCompileRate:.6,p95LatencyMs:150},completeRegressions:0,latencyBudgetMs:200})).toBe("PROMOTE")})
  test("keeps zero-evidence evaluation inconclusive",()=>expect(evaluateGlobalPremisePromotion({baseline:{kernelAcceptedRate:0,proofCompileRate:0,p95LatencyMs:0},candidate:{kernelAcceptedRate:0,proofCompileRate:0,p95LatencyMs:0},completeRegressions:0,latencyBudgetMs:200})).toBe("INCONCLUSIVE"))
})
