import { describe,expect,test } from "bun:test"
import { mkdtempSync } from "node:fs"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { MathOS } from "@mathos/core"
import { runHeadless } from "../apps/tui/src/headless.ts"
import { SLASH_COMMANDS } from "../apps/tui/src/slash.ts"

describe("proof portfolio CLI",()=>{test("returns versioned status and cancellation snapshots without raw provider data",async()=>{const root=mkdtempSync(join(tmpdir(),"mathos-portfolio-cli-"));await MathOS.init(root);const app=MathOS.open(root);app.services.repositories.proofPortfolios.insert({id:"PF-1",claimId:"C-1",formalStatementId:"F-1",formalRevisionHash:"h",branchId:"B-000",status:"RUNNING",selectionPolicy:{premiseMode:"RANKED"},limits:{maxWorkers:1},usage:{},retrievalIndexRevision:"IR-1",contextRevisionId:"CR-1",winnerCandidateId:null,revision:1,createdAt:"now",startedAt:"now",stoppedAt:null,stopReason:null});app.services.repositories.proofJobs.insert({id:"PJ-1",portfolioId:"PF-1",adapterId:"lean",adapterVersion:"1",strategy:"direct",workerBranchId:"b",worktreePath:"w",status:"RUNNING",idempotencyKey:"k",budget:{attempts:2},provider:null,model:null,promptHash:null,createdAt:"now",startedAt:"now",finishedAt:null,errorCode:null});app.close();const previous=process.cwd();process.chdir(root);let output="";const write=process.stdout.write.bind(process.stdout);process.stdout.write=((chunk:string|Uint8Array)=>{output+=String(chunk);return true})as typeof process.stdout.write;try{expect(await runHeadless(["portfolio","status","PF-1"])).toBe(0);const status=JSON.parse(output);expect(status.schemaVersion).toBe("mathos.proof-portfolio.v1");expect(status.trust.promotionAuthority).toBe("VerificationGate");expect(output).not.toContain("apiResponse");output="";expect(await runHeadless(["portfolio","cancel","PF-1"])).toBe(0);expect(JSON.parse(output).portfolio.status).toBe("CANCELLED");expect(SLASH_COMMANDS.map(item=>item.name)).toEqual(expect.arrayContaining(["portfolio","failures"]))}finally{process.stdout.write=write;process.chdir(previous)}})})
