import { afterEach, describe, expect, test } from "bun:test"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { DatabaseClient, PortfolioBudgetRepository, PortfolioLeaseRepository, ProofCandidateRepository, ProofJobRepository, ProofPortfolioRepository } from "@mathos/storage"
import { ProofPortfolioService } from "../packages/core/src/services/proof-portfolio-service.ts"

const clients:DatabaseClient[]=[]
function setup(){
  const client=new DatabaseClient(join(tmpdir(),`mathos-candidates-${crypto.randomUUID()}.sqlite`));client.migrate();clients.push(client)
  const portfolios=new ProofPortfolioRepository(client.db),jobs=new ProofJobRepository(client.db),candidates=new ProofCandidateRepository(client.db),budgets=new PortfolioBudgetRepository(client.db),leases=new PortfolioLeaseRepository(client.db)
  const artifacts=new Map<string,string>(),aborted:string[]=[];let id=0
  const service=new ProofPortfolioService({root:tmpdir(),portfolios,jobs,candidates,budgets,leases,unitOfWork:(work)=>client.unitOfWork(work),now:()=>"2030-01-01",nextId:(p)=>`${p}-${++id}`,createWorker:async({gitRef,worktreePath})=>({branchId:gitRef,worktreePath}),startProcess:async()=>({processId:"p"}),storeProofArtifact:(candidateId,source)=>{artifacts.set(candidateId,source);return `artifact:${candidateId}`},abortJob:async(jobId)=>{aborted.push(jobId)}})
  const start=()=>service.start({id:"PF-1",claimId:"C-1",formalStatementId:"F-1",formalRevisionHash:"formal-hash",contextRevisionId:"CR-1",retrievalIndexRevision:"IR-1",branchId:"B-1",maxWorkers:3,premiseMode:"RANKED",recipes:[{adapterId:"a",adapterVersion:"1",strategy:"one",budget:1},{adapterId:"b",adapterVersion:"1",strategy:"two",budget:1},{adapterId:"c",adapterVersion:"1",strategy:"three",budget:1}]})
  return{service,start,portfolios,jobs,candidates,artifacts,aborted}
}
afterEach(()=>{while(clients.length)clients.pop()!.close()})
const formal="theorem target : True"
const valid="theorem target : True := by\n  trivial"

describe("proof candidate policy",()=>{
  test("deduplicates whitespace-equivalent proofs while preserving the original artifact",async()=>{const s=setup();await s.start();const first=await s.service.evaluateCandidate({portfolioId:"PF-1",jobId:"PF-1-J001",formalDeclaration:formal,proofSource:valid,modelCallCost:2,compile:{result:"KERNEL_ACCEPTED",axioms:[],diagnostics:[]},verificationGatePassed:true});const duplicate=await s.service.evaluateCandidate({portfolioId:"PF-1",jobId:"PF-1-J002",formalDeclaration:formal,proofSource:" theorem  target : True := by   trivial ",modelCallCost:1,compile:{result:"KERNEL_ACCEPTED",axioms:[],diagnostics:[]},verificationGatePassed:true});expect(duplicate.id).toBe(first.id);expect(s.candidates.list()).toHaveLength(1);expect(s.artifacts.get(first.id)).toBe(valid)})
  test("rejects statement mutation and does not cancel workers for an invalid early candidate",async()=>{const s=setup();await s.start();const candidate=await s.service.evaluateCandidate({portfolioId:"PF-1",jobId:"PF-1-J001",formalDeclaration:formal,proofSource:"theorem target : False := by trivial",modelCallCost:1,compile:{result:"KERNEL_ACCEPTED",axioms:[],diagnostics:[]},verificationGatePassed:true});expect(candidate.status).toBe("REJECTED");expect(candidate.compileResult).toBe("STATEMENT_MUTATED");expect(s.aborted).toEqual([]);expect(s.jobs.list("PF-1").filter(j=>j.status==="RUNNING")).toHaveLength(2)})
  test("requires kernel, axiom, forbidden, and verification gates",async()=>{const s=setup();await s.start();const bad=await s.service.evaluateCandidate({portfolioId:"PF-1",jobId:"PF-1-J001",formalDeclaration:formal,proofSource:"theorem target : True := by sorry",modelCallCost:1,compile:{result:"KERNEL_ACCEPTED",axioms:["custom.axiom"],diagnostics:[]},verificationGatePassed:false});expect(bad.status).toBe("REJECTED");expect(bad.forbidden).toContain("sorry");await expect(s.service.finalizeWinner("PF-1")).rejects.toThrow("NO_VALID_PROOF_CANDIDATE")})
  test("selects deterministically by proof size, model cost, then stable id and cancels only afterward",async()=>{const s=setup();await s.start();const longer=await s.service.evaluateCandidate({id:"PC-B",portfolioId:"PF-1",jobId:"PF-1-J001",formalDeclaration:formal,proofSource:"theorem target : True := by\n  exact True.intro",modelCallCost:1,compile:{result:"KERNEL_ACCEPTED",axioms:[],diagnostics:[]},verificationGatePassed:true});const shorter=await s.service.evaluateCandidate({id:"PC-A",portfolioId:"PF-1",jobId:"PF-1-J002",formalDeclaration:formal,proofSource:valid,modelCallCost:5,compile:{result:"KERNEL_ACCEPTED",axioms:[],diagnostics:[]},verificationGatePassed:true});expect(s.aborted).toEqual([]);const winner=await s.service.finalizeWinner("PF-1");expect(winner.id).toBe(shorter.id);expect(winner.id).not.toBe(longer.id);expect(s.portfolios.get("PF-1")?.winnerCandidateId).toBe(shorter.id);expect(s.aborted).toEqual(["PF-1-J003"]);expect(s.jobs.list("PF-1").filter(j=>j.status==="CANCELLED")).toHaveLength(1)})
  test("allows user choice only among valid candidates",async()=>{const s=setup();await s.start();const validCandidate=await s.service.evaluateCandidate({id:"PC-VALID",portfolioId:"PF-1",jobId:"PF-1-J001",formalDeclaration:formal,proofSource:valid,modelCallCost:1,compile:{result:"KERNEL_ACCEPTED",axioms:[],diagnostics:[]},verificationGatePassed:true});const invalid=await s.service.evaluateCandidate({id:"PC-BAD",portfolioId:"PF-1",jobId:"PF-1-J002",formalDeclaration:formal,proofSource:"theorem target : False := by trivial",modelCallCost:0,compile:{result:"FAILED",axioms:[],diagnostics:[]},verificationGatePassed:false});await expect(s.service.finalizeWinner("PF-1",invalid.id)).rejects.toThrow("INVALID_USER_SELECTED_CANDIDATE");expect((await s.service.finalizeWinner("PF-1",validCandidate.id)).id).toBe(validCandidate.id)})
})
