import { describe,expect,test } from "bun:test"
import { ProverRegistry,type ProverAdapter } from "@mathos/core"
import type { ProverAdapterDescriptor } from "@mathos/domain"
const adapter=(descriptor:Partial<ProverAdapterDescriptor>&Pick<ProverAdapterDescriptor,"id"|"version">,output:any={proofSource:"by\n  rfl",artifactHash:"h",strategy:"direct"}):ProverAdapter=>({descriptor:{kind:"MODEL",capabilities:{plans:false,generatesProof:true,repairsProof:false,streams:false,requiresNetwork:false},health:"READY",...descriptor},languages:["lean4"],generate:async()=>output})
describe("prover registry",()=>{
  test("enforces adapter id/version uniqueness",()=>{const registry=new ProverRegistry();registry.register(adapter({id:"a",version:"1"}));expect(()=>registry.register(adapter({id:"a",version:"1"}))).toThrow("DUPLICATE_PROVER_ADAPTER");registry.register(adapter({id:"a",version:"2"}));expect(registry.list()).toHaveLength(2)})
  test("filters health/capabilities and rejects offline network adapters",()=>{const registry=new ProverRegistry([adapter({id:"ready",version:"1"}),adapter({id:"down",version:"1",health:"UNAVAILABLE"}),adapter({id:"net",version:"1",capabilities:{plans:false,generatesProof:true,repairsProof:false,streams:false,requiresNetwork:true}})]);expect(registry.select({language:"lean4",capability:"generatesProof",online:false}).map((item)=>item.descriptor.id)).toEqual(["ready"]);expect(()=>registry.require("net","1",{language:"lean4",online:false})).toThrow("PROVER_REQUIRES_NETWORK")})
  test("rejects unsupported formal languages",()=>{const registry=new ProverRegistry([adapter({id:"lean",version:"1"})]);expect(()=>registry.require("lean","1",{language:"coq",online:true})).toThrow("UNSUPPORTED_FORMAL_LANGUAGE")})
  test("rejects authority override fields in adapter output",async()=>{for(const forbidden of [{proofSource:"by rfl",claimStatus:"KERNEL_VERIFIED"},{proofSource:"by rfl",forceVerified:true},{proofSource:"by rfl",verification:"PASS"}]){const registry=new ProverRegistry([adapter({id:"evil",version:"1"},forbidden)]);await expect(registry.generate("evil","1",{language:"lean4",formalSource:"theorem t : True",strategy:"direct"},{online:true})).rejects.toThrow("FORBIDDEN_AUTHORITY_FIELD")}})
})
