import{afterEach,describe,expect,test}from"bun:test";import{mkdtempSync,readFileSync,rmSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";import{MODEL_PROFILE_V2_SCHEMA,ProviderDiscoveryCache,ProviderDiscoveryService,providerCatalog,type ModelProfileV2}from"@mathos/models"
const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true})))
function setup(now:{value:number}){const root=mkdtempSync(join(tmpdir(),"mathos-discovery-"));roots.push(root);const path=join(root,"cache.json");return{path,cache:new ProviderDiscoveryCache(path,()=>now.value)}}
function profile(model:string):ModelProfileV2{return{schemaVersion:MODEL_PROFILE_V2_SCHEMA,id:"p",descriptorId:"openai-api",displayName:"P",model,endpointPresetId:null,baseUrlOverride:null,auth:{kind:"secret-ref",secretRef:"model.p"},enabled:true,timeoutMs:1000,maxResponseBytes:1000,maxOutputTokens:null,reasoningEffort:null,allowedRoles:[],requestConcurrency:1,metadata:{createdAt:"2026-01-01T00:00:00Z",updatedAt:"2026-01-01T00:00:00Z",migratedFromV1:false}}}
describe("provider discovery",()=>{
 test("uses authoritative runtime list, TTL cache, refresh, and redacted persistence",async()=>{const now={value:1_000},{path,cache}=setup(now);let calls=0;const service=new ProviderDiscoveryService(cache,async()=>{calls++;return{data:[{id:"model-b",accountEmail:"person@example.com",token:"secret-canary"},{id:"model-a"}]}},100);const descriptor=providerCatalog.get("openai-api")!;const first=await service.discover(descriptor,profile("model-a"));expect(first.source).toBe("runtime");expect(first.models.map(row=>row.id)).toEqual(["model-a","model-b"]);expect(first.selectedModel).toBe("model-a");expect(await service.discover(descriptor,profile("model-a"))).toEqual(expect.objectContaining({source:"cache"}));expect(calls).toBe(1);expect(readFileSync(path,"utf8")).not.toMatch(/secret-canary|person@example.com/);await service.discover(descriptor,profile("model-a"),true);expect(calls).toBe(2)})
 test("uses stale cache on refresh failure and official static fallback otherwise",async()=>{const now={value:1_000},{cache}=setup(now),base=providerCatalog.get("openai-api")!,descriptor={...base,defaultModels:["official-model"]};const ok=new ProviderDiscoveryService(cache,async()=>[{id:"runtime-model"}],10);await ok.discover(descriptor,profile("runtime-model"));now.value+=20;const failed=new ProviderDiscoveryService(cache,async()=>{throw new Error("offline")},10);expect(await failed.discover(descriptor,profile("runtime-model"))).toEqual(expect.objectContaining({source:"stale-cache",stale:true}));const fresh=setup(now).cache;const fallback=await new ProviderDiscoveryService(fresh,async()=>{throw new Error("offline")}).discover(descriptor);expect(fallback.source).toBe("official-static");expect(fallback.reviewedAt).toBe(descriptor.terms.lastReviewedAt)})
 test("exact missing model errors while auto selects a new default",async()=>{const now={value:1_000},{cache}=setup(now),descriptor={...providerCatalog.get("openai-api")!,defaultModels:["model-new"]};const service=new ProviderDiscoveryService(cache,async()=>["model-new"]);await expect(service.discover(descriptor,profile("model-old"))).rejects.toThrow("PROFILE_MODEL_UNAVAILABLE");expect((await service.discover(descriptor,profile("auto"))).selectedModel).toBe("model-new")})
})
