import { afterEach,describe,expect,test } from "bun:test"
import { join } from "node:path";import{tmpdir}from"node:os"
import { DatabaseClient,SolverJobRepository,SolverResultRepository } from "@mathos/storage"
import { SolverAdapterRegistry } from "../packages/core/src/services/solver-registry.ts"
import { SolverLabService } from "../packages/core/src/services/solver-lab-service.ts"
const clients:DatabaseClient[]=[]
function setup(raw:any={outcome:"SUPPORT",trustClass:"UNTRUSTED",inputHash:"ih",outputHash:"oh",exact:true}){const client=new DatabaseClient(join(tmpdir(),`solver-lab-${crypto.randomUUID()}.sqlite`));client.migrate();clients.push(client);const registry=new SolverAdapterRegistry();registry.register({descriptor:{id:"fake",version:"1",health:"READY",problemKinds:["TEST"],maxTrustClass:"CERTIFICATE_CHECKED"},solve:async()=>raw});let id=0;const evidence:any[]=[];const service=new SolverLabService({registry,jobs:new SolverJobRepository(client.db),results:new SolverResultRepository(client.db),artifacts:{put:(key:string)=>key,get:()=>null,exists:()=>true},unitOfWork:(work)=>client.unitOfWork(work),now:()=>"2030",nextId:(p)=>`${p}-${++id}`,validateWitness:(w)=>(w as {valid?:boolean}|null)?.valid===true,validateCertificate:(c)=>c==="valid-cert",leanReplay:async()=>({passed:false,inputHash:"",outputHash:""}),createEvidence:(row)=>{evidence.push(row);return`E-${evidence.length}`}});return{service,client,evidence}}
afterEach(()=>{while(clients.length)clients.pop()!.close()})
describe("solver lab",()=>{test("persists job/result evidence without changing the claim",async()=>{const s=setup();const claim={status:"CONJECTURE"};const result=await s.service.run({id:"SJ-1",workspaceId:"W-1",branchId:"B-1",claimId:"C-1",solverId:"fake",problemKind:"TEST",payload:{x:1},policy:{networkAllowed:false,timeoutMs:100,maxOutputBytes:1000,executableAllowlist:[]}});expect(result.job.status).toBe("SUCCEEDED");expect(result.result.trustClass).toBe("UNTRUSTED");expect(claim.status).toBe("CONJECTURE");expect(s.evidence).toHaveLength(1)});test("independently validates counterexample witnesses",async()=>{const invalid=setup({outcome:"COUNTEREXAMPLE",trustClass:"WITNESS_CHECKED",witness:{valid:false},inputHash:"i",outputHash:"o",exact:true});expect((await invalid.service.run({id:"SJ-1",workspaceId:"W",branchId:"B",claimId:"C",solverId:"fake",problemKind:"TEST",payload:{},policy:{networkAllowed:false,timeoutMs:1,maxOutputBytes:1,executableAllowlist:[]}})).result.structured).toEqual(expect.objectContaining({errorCode:"INVALID_COUNTEREXAMPLE"}));const valid=setup({outcome:"COUNTEREXAMPLE",trustClass:"WITNESS_CHECKED",witness:{valid:true},inputHash:"i",outputHash:"o",exact:true});expect((await valid.service.run({id:"SJ-2",workspaceId:"W",branchId:"B",claimId:"C",solverId:"fake",problemKind:"TEST",payload:{},policy:{networkAllowed:false,timeoutMs:1,maxOutputBytes:1,executableAllowlist:[]}})).result.trustClass).toBe("WITNESS_CHECKED")});test("blocks unavailable adapters and records timeout terminally",async()=>{const s=setup({outcome:"ERROR",trustClass:"UNTRUSTED",errorCode:"SOLVER_TIMEOUT",inputHash:"i",outputHash:"o",exact:false});expect((await s.service.run({id:"SJ-1",workspaceId:"W",branchId:"B",claimId:null,solverId:"fake",problemKind:"TEST",payload:{},policy:{networkAllowed:false,timeoutMs:1,maxOutputBytes:1,executableAllowlist:[]}})).job.status).toBe("TIMED_OUT");await expect(s.service.run({id:"SJ-2",workspaceId:"W",branchId:"B",claimId:null,solverId:"missing",problemKind:"TEST",payload:{},policy:{networkAllowed:false,timeoutMs:1,maxOutputBytes:1,executableAllowlist:[]}})).rejects.toThrow("SOLVER_UNAVAILABLE")})})
