export { MathOS, type MathOSOptions } from "./mathos.ts"
export { buildDoctorReport, inspectPlatformCapabilities } from "./doctor.ts"
export type { PlatformCapabilityReport, PlatformReleaseClaim } from "./doctor.ts"
export { runResearchIntake } from "./intake.ts"
export { parseFormalizationDraft } from "./formalize.ts"
export { parseFidelityPayload } from "./fidelity.ts"
export { parseProofBody } from "./prove.ts"
export { runVerificationGate } from "./verify.ts"
export { FakeResearchPlanner, ModelResearchPlanner, type ResearchPlanner } from "./research-planner.ts"
export { PersistentScriptedPlanner, createPlannerFromDescriptor } from "./planner-factory.ts"
export { FakeMultiAgentPlanner, ModelMultiAgentPlanner, type MultiAgentPlanner } from "./multi-agent-planner.ts"
export { TeamResearchCoordinator, type TeamResearchCoordinatorDependencies } from "./services/team-research-coordinator.ts"
export { BranchService, type BranchServiceDependencies } from "./services/branch-service.ts"
export { ResearchQueryService, type ResearchQueryServiceDependencies } from "./services/research-query-service.ts"
export { ClaimService, type ClaimServiceDependencies, type CreateClaimInput, type AddEvidenceInput, type AddBlockerInput } from "./services/claim-service.ts"
export { ProofService, type ProofServiceDependencies, type ProveOptions } from "./services/proof-service.ts"
export { RetrievalService, type RetrievalServiceDependencies, type ProofRetrievalResult } from "./services/retrieval-service.ts"
export { runResearchEval, runResearchScenario, RESEARCH_EVAL_SCENARIOS } from "./research-eval.ts"
export { loadRealResearchDataset, validateRealResearchDataset, REAL_RESEARCH_ROOT, type RealResearchCase, type RealResearchManifest } from "./evaluation/real-research-eval.ts"
export { runRealResearchCase, REAL_RESEARCH_BUDGET, normalizeLeanTarget, formalTargetMatches, isTimeoutReason, hasExplicitFidelityApproval, type FidelityApproval, type RealResearchCaseResult, type RealCaseStatus } from "./evaluation/research-case-runner.ts"
export { summarizeRealResearch, nondeterministicRegression, formatRealResearchReport, type RealResearchSummary } from "./evaluation/research-report.ts"
export { createDemoWorkspace } from "./product-demo.ts"
export * from "./product-ux.ts"
export { backupWorkspace, restoreWorkspace, eventLogHealth, exportDiagnostics, redactCanary } from "./release.ts"
export { createServiceContainer, type ServiceContainer, type ServiceContainerOverrides } from "./composition/service-container.ts"
export { FileArtifactStore, systemClock } from "./composition/built-in-adapters.ts"
export type { ClaimReadPort } from "./ports/claim-read-port.ts"
export type { FormalReadPort } from "./ports/formal-read-port.ts"
export type { GraphReadPort } from "./ports/graph-read-port.ts"
export type { ArtifactStorePort } from "./ports/artifact-store-port.ts"
export type { ClockPort } from "./ports/clock-port.ts"
export { MathematicalContextService, type MathematicalContextDependencies, type ContextScope, type ContextProposalInput } from "./services/mathematical-context-service.ts"
export { ContextBindingService, type ContextBindingScope } from "./services/context-binding-service.ts"
export { ResearchNotebookService, type ResearchNotebookDependencies, type CreateNotebookInput, type NotebookMutationResult } from "./services/research-notebook-service.ts"
export { StatementRevisionService, type StatementRevisionDependencies, type CaptureStatementRevision } from "./services/statement-revision-service.ts"
