import { createHash } from "node:crypto"
export interface OptionalSolverRunner{available(executable:string):Promise<boolean>;version(executable:string):Promise<string>;run(input:{executable:string;argv:string[];cwd:string;timeoutMs:number;env:Record<string,string>}):Promise<{stdout:string;stderr:string;exitCode:number|null;timedOut:boolean}>}
export interface OptionalSolverIo{createSandboxRoot():string;writeRequest(root:string,name:string,data:string):string}
export interface OptionalSolverRequest{problemKind:string;payload:Record<string,unknown>;timeoutMs:number}
const hash=(value:string)=>createHash("sha256").update(value).digest("hex")
export class OptionalProcessSolver{
  constructor(readonly descriptor:{id:string;version:string;executable:string;problemKinds:string[];maxTrustClass:string},private readonly runner:OptionalSolverRunner,private readonly io:OptionalSolverIo){}
  async doctor(){const available=await this.runner.available(this.descriptor.executable);return{...this.descriptor,health:available?"READY" as const:"UNAVAILABLE" as const,version:available?await this.runner.version(this.descriptor.executable):null}}
  async solve(request:OptionalSolverRequest){const root=this.io.createSandboxRoot(),serialized=JSON.stringify({schemaVersion:"mathos.solver-request.v1",problemKind:request.problemKind,payload:request.payload}),requestPath=this.io.writeRequest(root,"request.json",serialized),inputHash=hash(serialized);const run=await this.runner.run({executable:this.descriptor.executable,argv:[requestPath],cwd:root,timeoutMs:request.timeoutMs,env:{MATHOS_SOLVER_NETWORK:"deny"}});if(run.timedOut)return{outcome:"ERROR" as const,trustClass:"UNTRUSTED" as const,inputHash,outputHash:hash(run.stdout),errorCode:"SOLVER_TIMEOUT"};if(run.exitCode!==0)return{outcome:"ERROR" as const,trustClass:"UNTRUSTED" as const,inputHash,outputHash:hash(run.stdout),errorCode:"SOLVER_EXIT_NONZERO",diagnostics:[run.stderr]};try{const parsed=JSON.parse(run.stdout) as Record<string,unknown>;return{outcome:String(parsed.outcome) as "SUPPORT"|"COUNTEREXAMPLE"|"UNSAT"|"SAT"|"UNKNOWN"|"ERROR",trustClass:"UNTRUSTED" as const,inputHash,outputHash:hash(run.stdout),exact:parsed.exact===true,witness:parsed.witness,certificate:parsed.certificate,result:parsed.result,errorCode:null}}catch{return{outcome:"ERROR" as const,trustClass:"UNTRUSTED" as const,inputHash,outputHash:hash(run.stdout),errorCode:"MALFORMED_SOLVER_JSON"}}}
}
