import type { SecretMetadata, SecretRef, SecretStore, SecretStoreCapability, SecretCommandRunner } from "./types.ts"
import { validateSecretRef, validateSecretValue } from "./types.ts"
import { bunSecretCommandRunner } from "./command-runner.ts"

const SERVICE = "com.mathos.model-provider"
const prefix = `$ErrorActionPreference='Stop'; Add-Type -TypeDefinition @'\nusing System; using System.Runtime.InteropServices; public class MathOSCred { [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)] public struct C { public uint Flags; public uint Type; public string TargetName; public string Comment; public System.Runtime.InteropServices.ComTypes.FILETIME LastWritten; public uint CredentialBlobSize; public IntPtr CredentialBlob; public uint Persist; public uint AttributeCount; public IntPtr Attributes; public string TargetAlias; public string UserName; } [DllImport("Advapi32.dll", EntryPoint="CredWriteW", CharSet=CharSet.Unicode, SetLastError=true)] public static extern bool Write(ref C c,uint f); [DllImport("Advapi32.dll", EntryPoint="CredReadW", CharSet=CharSet.Unicode, SetLastError=true)] public static extern bool Read(string t,uint y,uint f,out IntPtr p); [DllImport("Advapi32.dll", EntryPoint="CredDeleteW", CharSet=CharSet.Unicode, SetLastError=true)] public static extern bool Delete(string t,uint y,uint f); [DllImport("Advapi32.dll")] public static extern void CredFree(IntPtr p); }\n'@; `

function target(ref: string): string { return `${SERVICE}:${validateSecretRef(ref)}` }
function encoded(script: string): string { return Buffer.from(script, "utf16le").toString("base64") }

export class WindowsCredentialManagerStore implements SecretStore {
  constructor(private readonly runner: SecretCommandRunner = bunSecretCommandRunner, private readonly executable = "powershell.exe") {}
  private run(script: string, stdin?: string) { return this.runner.run(this.executable, ["-NoProfile", "-NonInteractive", "-EncodedCommand", encoded(prefix + script)], stdin) }
  async capability(): Promise<SecretStoreCapability> { const result = await this.run("[Console]::Out.Write('ok')"); return { backend: "windows-credential-manager", readable: result.exitCode === 0, writable: result.exitCode === 0, detail: result.exitCode === 0 ? "Windows Credential Manager available" : "Windows Credential Manager unavailable" } }
  async set(ref: SecretRef, value: string): Promise<void> { const script = `$v=[Console]::In.ReadToEnd();$b=[Text.Encoding]::UTF8.GetBytes($v);$p=[Runtime.InteropServices.Marshal]::AllocHGlobal($b.Length);try{[Runtime.InteropServices.Marshal]::Copy($b,0,$p,$b.Length);$c=New-Object MathOSCred+C;$c.Type=1;$c.TargetName='${target(ref)}';$c.UserName='MathOS';$c.Persist=2;$c.CredentialBlobSize=$b.Length;$c.CredentialBlob=$p;if(-not [MathOSCred]::Write([ref]$c,0)){throw 'write'}}finally{[Runtime.InteropServices.Marshal]::ZeroFreeGlobalAllocAnsi($p)}`; const result = await this.run(script, validateSecretValue(value)); if (result.exitCode !== 0) throw new Error("SECRET_STORE_WRITE_FAILED") }
  async get(ref: SecretRef): Promise<string | null> { const script = `$p=[IntPtr]::Zero;if(-not [MathOSCred]::Read('${target(ref)}',1,0,[ref]$p)){if([Runtime.InteropServices.Marshal]::GetLastWin32Error()-eq 1168){exit 44};throw 'read'};try{$c=[Runtime.InteropServices.Marshal]::PtrToStructure($p,[type][MathOSCred+C]);$b=New-Object byte[] $c.CredentialBlobSize;[Runtime.InteropServices.Marshal]::Copy($c.CredentialBlob,$b,0,$b.Length);[Console]::Out.Write([Text.Encoding]::UTF8.GetString($b))}finally{[MathOSCred]::CredFree($p)}`; const result = await this.run(script); if (result.exitCode === 44) return null; if (result.exitCode !== 0) throw new Error("SECRET_STORE_READ_FAILED"); return result.stdout || null }
  async delete(ref: SecretRef): Promise<void> { const result = await this.run(`if(-not [MathOSCred]::Delete('${target(ref)}',1,0)){if([Runtime.InteropServices.Marshal]::GetLastWin32Error()-ne 1168){throw 'delete'}}`); if (result.exitCode !== 0) throw new Error("SECRET_STORE_DELETE_FAILED") }
  async listMetadata(refs: SecretRef[] = []): Promise<SecretMetadata[]> { return Promise.all(refs.map(async ref => ({ ref: validateSecretRef(ref), configured: Boolean(await this.get(ref)), backend: "windows-credential-manager" as const }))) }
}
