import{existsSync}from"node:fs";import{homedir}from"node:os";import{dirname,join}from"node:path";import{CopilotClient,RuntimeConnection}from"@github/copilot-sdk"
export interface CopilotSdkSession{sendAndWait(input:{prompt:string},timeout?:number):Promise<any>;disconnect():Promise<void>}
export interface CopilotSdkAdapter{start():Promise<void>;stop():Promise<unknown>;listModels():Promise<any[]>;createSession(config:Record<string,unknown>):Promise<CopilotSdkSession>}
export interface CopilotAdapterOptions{cliPath?:string|null;env?:NodeJS.ProcessEnv}
/**
 * Empty mode (deny-wins tool filtering) requires an explicit Copilot home; the user's own home keeps the sign-in made
 * with `copilot` -> /login. A compiled MathOS ships no bundled Copilot runtime package, so it falls back to the CLI the
 * user installed and signed in with.
 */
export function createOfficialCopilotAdapter(options:CopilotAdapterOptions={}):CopilotSdkAdapter{const env=options.env??process.env,base={mode:"empty" as const,useLoggedInUser:true,baseDirectory:env.COPILOT_HOME||join(env.HOME??env.USERPROFILE??homedir(),".copilot")};try{return new CopilotClient(base) as unknown as CopilotSdkAdapter}catch(error){if(!options.cliPath||!/@github\/copilot platform package/i.test(error instanceof Error?error.message:String(error)))throw error;return new CopilotClient({...base,connection:RuntimeConnection.forStdio({path:copilotCliPath(options.cliPath),env:Object.fromEntries(Object.entries(env).filter((entry):entry is [string,string]=>typeof entry[1]==="string"))})}) as unknown as CopilotSdkAdapter}}
/** npm's Windows `.cmd` shim cannot be spawned directly; its package entry point runs under node instead. */
export function copilotCliPath(found:string,platform:NodeJS.Platform=process.platform):string{if(platform!=="win32"||!/\.(cmd|bat|ps1)$/i.test(found))return found;const entry=join(dirname(found),"node_modules","@github","copilot","index.js");return existsSync(entry)?entry:found}
export class CopilotSdkBridge{constructor(private readonly client:CopilotSdkAdapter=createOfficialCopilotAdapter()){}async start(){try{await this.client.start()}catch(error){throw normalizeCopilotError(error)}}async stop(){await this.client.stop()}async models(){try{return(await this.client.listModels()).map(model=>({id:String(model.id),name:String(model.name??model.id),capabilities:model.capabilities??{},billing:model.billing??null}))}catch(error){throw normalizeCopilotError(error)}}async prompt(model:string|undefined,text:string,timeoutMs?:number){let session:CopilotSdkSession|null=null;try{session=await this.client.createSession({clientName:"MathOS",model,availableTools:[],excludedTools:["*"],mcpServers:{},customAgents:[],skillDirectories:[],reasoningSummary:"none"});const response=await session.sendAndWait({prompt:text},timeoutMs);const content=response?.data?.content??response?.content;if(typeof content!=="string"||!content)throw new Error("COPILOT_RESPONSE_EMPTY");return{text:content,usage:response?.data?.usage??response?.usage??null}}catch(error){throw normalizeCopilotError(error)}finally{await session?.disconnect().catch(()=>undefined)}}}
export function normalizeCopilotError(error:unknown):Error{const message=error instanceof Error?error.message:String(error);if(/not authenticated|authenticate first|not logged in/i.test(message))return new Error("COPILOT_LOGIN_REQUIRED");if(/subscription|entitlement|not authorized|login|authentication/i.test(message))return new Error("COPILOT_SUBSCRIPTION_REQUIRED");return error instanceof Error?error:new Error(message)}
