import { createHash } from "node:crypto"
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import baseline from "../benchmarks/software-completion-v2-baseline.json"

export type GateStatus="PASS"|"FAIL"|"SKIPPED_UNSUPPORTED_PLATFORM"|"PENDING_EXTERNAL_VALIDATION"
export interface GateResult{id:string;status:GateStatus;evidence:{command:string[];exitCode:number|null;outputHash:string;summary?:string};sourceRevision:string;artifactHashes:Record<string,string>}
const sha=(value:string|Uint8Array)=>createHash("sha256").update(value).digest("hex")
export function evaluateSoftwareCompletion(results:GateResult[],sourceRevision:string,knownSoftwareBlockers:string[]=[]){const ids=baseline.requiredGateIds,by=new Map(results.map(row=>[row.id,row])),duplicate=results.length!==by.size,checks=ids.map(id=>by.get(id)??{id,status:"FAIL" as const,evidence:{command:[],exitCode:null,outputHash:"",summary:"MISSING_GATE"},sourceRevision,artifactHashes:{}}),forbidden=new RegExp(baseline.forbiddenEvidencePatterns.join("|"),"i"),blockers=[...knownSoftwareBlockers];if(duplicate)blockers.push("DUPLICATE_GATE");if(results.some(row=>!ids.includes(row.id)))blockers.push("UNKNOWN_GATE");for(const row of checks){if(row.status!=="PASS")blockers.push(`${row.id}:${row.status}`);if(row.sourceRevision!==sourceRevision)blockers.push(`${row.id}:STALE_REVISION`);if(!row.evidence.command.length||row.evidence.exitCode!==0||!/^\w{64}$/.test(row.evidence.outputHash)||forbidden.test(JSON.stringify(row.evidence)))blockers.push(`${row.id}:INVALID_EVIDENCE`);if(!Object.keys(row.artifactHashes).length||Object.values(row.artifactHashes).some(hash=>!/^\w{64}$/.test(hash)))blockers.push(`${row.id}:ARTIFACT_HASH_INVALID`)}return{schemaVersion:"mathos.software-completion-v2",version:baseline.requiredVersion,sourceRevision,checks,passCount:checks.filter(row=>row.status==="PASS").length,total:ids.length,knownSoftwareBlockers:[...new Set(blockers)],externalValidation:{paidModelProvider:"PENDING_EXTERNAL_VALIDATION",marketplacePublisher:"PENDING_EXTERNAL_VALIDATION",notarization:"PENDING_EXTERNAL_VALIDATION",professionalHumanPilot:"PENDING_EXTERNAL_VALIDATION"},ready:checks.length===22&&blockers.length===0}}

const root=resolve(import.meta.dir,".."),bun=process.execPath
const gates:Record<string,string[][]>={
G01:[[bun,"test","tests/version-contract.test.ts","tests/release-manifest.test.ts"]],
G02:[[bun,"run","typecheck"],[bun,"run","build"],[bun,"run","build:atlas"],[bun,"run","build:vscode"]],
G03:[[bun,"test"]],G04:[[bun,"test","tests/verification-trust.test.ts","tests/verification-authority.test.ts"]],
G05:[[bun,"run","release:build"],[bun,"test","tests/package-smoke.test.ts"]],G06:[[bun,"run","release:verify"]],
G07:[[bun,"test","tests/distribution-layout.test.ts","tests/no-source-tree-runtime-dependency.test.ts"]],
G08:[[bun,"test","tests/setup-state.test.ts","tests/setup-resume.test.ts","tests/setup-doctor.test.ts"]],
G09:[[bun,"test","tests/config-layering.test.ts","tests/secret-store.test.ts","tests/secret-redaction-e2e.test.ts","tests/capsule-secret-scan.test.ts","tests/diagnostics-redaction.test.ts"]],
G10:[[bun,"test","tests/lean-setup-contract.test.ts","tests/version-contract.test.ts","tests/verification-trust.test.ts"]],
G11:[[bun,"test","tests/sandbox.test.ts","tests/sandbox-security.test.ts"]],
G12:[[bun,"test","tests/model-profile.test.ts","tests/model-routing.test.ts","tests/model-retry.test.ts","tests/model-cancellation.test.ts","tests/model-privacy.test.ts","tests/model-secret-redaction.test.ts"]],
G13:[[bun,"test","tests/literature-providers.test.ts","tests/literature-dedupe.test.ts","tests/literature-cache.test.ts","tests/literature-offline.test.ts","tests/literature-registry.test.ts"]],
G14:[[bun,"test","tests/workspace-migration-rc.test.ts","tests/workspace-backup-rc.test.ts","tests/workspace-lock.test.ts","tests/workspace-repair.test.ts","tests/stale-write.test.ts"]],
G15:[[bun,"test","tests/bridge-protocol.test.ts","tests/bridge-version.test.ts","tests/bridge-cancellation.test.ts","tests/bridge-security.test.ts","tests/bridge-workspace-boundary.test.ts"]],
G16:[[bun,"test","tests/cli-contract.test.ts","tests/headless-json-contract.test.ts","tests/tui-final-smoke.test.tsx","tests/tui-smoke.test.tsx"]],
G17:[[bun,"test","tests/atlas-snapshot.test.ts","tests/atlas-server-security.test.ts","tests/atlas-large-graph.test.ts","tests/atlas-projection.test.ts"]],
G18:[[bun,"run","vscode:package"],[bun,"run","vscode:verify"],[bun,"test","tests/vscode-package-manifest.test.ts","tests/vscode-bridge-contract.test.ts","tests/vscode-workspace-trust.test.ts"]],
G19:[[bun,"test","tests/plugin-lifecycle.test.ts","tests/plugin-manifest.test.ts","tests/plugin-process-host.test.ts","tests/plugin-conformance.test.ts","tests/plugin-adapters.test.ts"]],
G20:[[bun,"test","tests/capsule-format-v1.test.ts","tests/capsule-import-dry-run.test.ts","tests/capsule-secret-scan.test.ts","tests/capsule-roundtrip.test.ts","tests/publication-determinism.test.ts","tests/publication-epistemic-status.test.ts","tests/publication-citation-audit.test.ts"]],
G21:[[bun,"test","tests/updater-manifest.test.ts","tests/updater-checksum.test.ts","tests/updater-rollback.test.ts","tests/uninstall-preserves-workspaces.test.ts"]],
G22:[[bun,"install","--frozen-lockfile"],[bun,"scripts/product-scale-benchmark.ts"],[bun,"run","release:verify"]]}
async function execute(){const rev=Bun.spawnSync(["git","rev-parse","HEAD"],{cwd:root,stdout:"pipe"}).stdout.toString().trim(),dirty=Bun.spawnSync(["git","status","--porcelain","--untracked-files=no"],{cwd:root,stdout:"pipe"}).stdout.toString().trim(),results:GateResult[]=[];for(const id of baseline.requiredGateIds){const commands=gates[id]??[],outputs:string[]=[];let exitCode=0;for(const command of commands){const proc=Bun.spawnSync(command,{cwd:root,stdout:"pipe",stderr:"pipe",env:{...process.env,NO_COLOR:"1",FORCE_COLOR:"0"}});const text=proc.stdout.toString()+proc.stderr.toString();outputs.push(text);if(proc.exitCode!==0){exitCode=proc.exitCode;break}}if(id==="G01"&&dirty){exitCode=1;outputs.push(`DIRTY_TRACKED_TREE:${dirty}`)}const output=outputs.join("\n"),hash=sha(output);results.push({id,status:exitCode===0?"PASS":"FAIL",evidence:{command:commands.flat(),exitCode,outputHash:hash,summary:output.slice(-1000)},sourceRevision:rev,artifactHashes:{commandOutput:hash}});process.stderr.write(`${id} ${exitCode===0?"PASS":"FAIL"}\n`)}const report=evaluateSoftwareCompletion(results,rev),dir=resolve(root,"artifacts/qualification");mkdirSync(dir,{recursive:true});writeFileSync(resolve(dir,"software-completion-v2.json"),JSON.stringify(report,null,2));writeFileSync(resolve(dir,"software-completion-v2.md"),`# Software Completion V2\n\nReady: ${report.ready}\nSource: ${rev}\n\n${report.checks.map(row=>`- ${row.id}: ${row.status}`).join("\n")}\n\nBlockers: ${report.knownSoftwareBlockers.join(", ")||"none"}\n`);return report}
if(import.meta.main){const report=await execute();console.log(JSON.stringify(report,null,2));if(!report.ready)process.exit(1)}
