import{descriptor}from"./presets-core.ts";import type{ProviderDescriptor,ProviderModelProtocol,ProviderWireProtocol}from"./types.ts"
// OpenCode Zen (PAYG) and OpenCode Go (subscription) are multi-protocol gateways: one API key, and each model is served over
// the wire protocol listed in the official endpoint tables (opencode.ai/docs/zen, opencode.ai/docs/go, reviewed 2026-09-24).
// Models absent from the tables fall back to chat completions; Gemini-native and "systemone" endpoints are not supported.
type Row=[string,ProviderWireProtocol|"unsupported"]
const rows=(items:Row[]):ProviderModelProtocol[]=>items.map(([model,protocol])=>({model,protocol}))
const GO:Row[]=[["grok-4.7","openai-responses"],["grok-4.6","openai-responses"],["gpt-6-luna","openai-responses"],["gpt-5.6-luna","openai-responses"],["glm-5.3-flash","openai-chat"],["glm-5.3","openai-chat"],["glm-5.2","openai-chat"],["glm-5.1","openai-chat"],["kimi-k3","openai-chat"],["kimi-k2.7-code","openai-chat"],["kimi-k2.6","openai-chat"],["longcat-2.0","openai-chat"],["deepseek-v4.1-flash","openai-chat"],["deepseek-v4-pro","openai-chat"],["deepseek-v4-flash","openai-chat"],["deepseek-v4-flash-vision-exp","openai-chat"],["mimo-v2.6-flash","openai-chat"],["mimo-v2.6-pro","openai-chat"],["mimo-v2.5","openai-chat"],["mimo-v2.5-pro","openai-chat"],["minimax-m3","anthropic-messages"],["minimax-m2.7","anthropic-messages"],["minimax-m2.5","anthropic-messages"],["muse-spark-1.3-contributor","openai-responses"],["muse-spark-1.2-contributor","openai-responses"],["qwen3.8-max","anthropic-messages"],["qwen3.8-flash","anthropic-messages"],["qwen3.7-max","anthropic-messages"],["qwen3.7-plus","anthropic-messages"],["qwen3.6-plus","anthropic-messages"],["hy4-preview","openai-chat"],["hy3","openai-chat"],["space-bunny-free","openai-chat"]]
const ZEN:Row[]=[["gpt-6-astra","openai-responses"],["gpt-6-sol","openai-responses"],["gpt-6-luna","openai-responses"],["gpt-5.6-sol","openai-responses"],["gpt-5.6-terra","openai-responses"],["gpt-5.6-luna","openai-responses"],["gpt-5.5","openai-responses"],["gpt-5.5-pro","openai-responses"],["gpt-5.4","openai-responses"],["gpt-5.4-pro","openai-responses"],["gpt-5.4-mini","openai-responses"],["gpt-5.4-nano","openai-responses"],["gpt-5.3-codex","openai-responses"],["gpt-5.3-codex-spark","openai-responses"],["gpt-5.2","openai-responses"],["gpt-5.2-codex","openai-responses"],["gpt-5.1","openai-responses"],["gpt-5.1-codex","openai-responses"],["gpt-5.1-codex-max","openai-responses"],["gpt-5.1-codex-mini","openai-responses"],["gpt-5","openai-responses"],["gpt-5-codex","openai-responses"],["gpt-5-nano","openai-responses"],["claude-fable-5-1","anthropic-messages"],["claude-fable-5","anthropic-messages"],["claude-opus-5-5","anthropic-messages"],["claude-opus-5","anthropic-messages"],["claude-opus-4-8","anthropic-messages"],["claude-opus-4-7","anthropic-messages"],["claude-opus-4-6","anthropic-messages"],["claude-opus-4-5","anthropic-messages"],["claude-sonnet-5","anthropic-messages"],["claude-sonnet-4-6","anthropic-messages"],["claude-sonnet-4-5","anthropic-messages"],["claude-haiku-4-5","anthropic-messages"],["gemini-3.8-flash","unsupported"],["gemini-3.7-flash","unsupported"],["gemini-3.6-flash","unsupported"],["gemini-3.5-flash","unsupported"],["gemini-3.5-flash-lite","unsupported"],["gemini-3.1-pro","unsupported"],["gemini-3-flash","unsupported"],["grok-4.7","openai-responses"],["grok-4.6","openai-responses"],["grok-4.5","openai-responses"],["grok-build-0.1","openai-responses"],["muse-spark-1.3","openai-responses"],["muse-spark-1.2","openai-responses"],["qwen3.8-flash","anthropic-messages"],["qwen3.7-max","anthropic-messages"],["qwen3.7-plus","anthropic-messages"],["qwen3.6-plus","anthropic-messages"],["qwen3.5-plus","anthropic-messages"],["deepseek-v4.1-flash","openai-chat"],["deepseek-v4-pro","openai-chat"],["deepseek-v4-flash","openai-chat"],["deepseek-v4-flash-vision-exp","openai-chat"],["minimax-m3","openai-chat"],["minimax-m2.7","openai-chat"],["minimax-m2.5","openai-chat"],["glm-5.3-flash","openai-chat"],["glm-5.3","openai-chat"],["glm-5.2","openai-chat"],["glm-5.1","openai-chat"],["glm-5","openai-chat"],["kimi-k2.5","openai-chat"],["kimi-k2.6","openai-chat"],["kimi-k2.7-code","openai-chat"],["kimi-k3","openai-chat"],["jev-1.13","unsupported"],["jev-1.13-free","unsupported"],["big-pickle","openai-chat"],["space-bunny-free","openai-chat"],["mimo-v2.6-flash-free","openai-chat"],["mimo-v2.5-free","openai-chat"],["ling-3.0-flash-fin-free","openai-chat"],["nemotron-3-ultra-free","openai-chat"],["nemotron-3.5-lightning-free","openai-chat"],["muse-spark-1.3-contributor-free","openai-responses"]]
const identity={userAgent:true as const,sessionHeader:"x-opencode-session"}
export const GATEWAY_PROVIDER_PRESETS:ProviderDescriptor[]=[
 {...descriptor({id:"opencode-go",name:"OpenCode Go",vendor:"OpenCode",category:"plan",transport:"openai-chat",billing:"subscription",url:"https://opencode.ai/zen/go/v1",source:"https://opencode.ai/docs/go/",policy:"SCOPED_PLAN",summary:"Subscription for coding-agent style traffic. Clients must send their own User-Agent and a stable x-opencode-session per conversation; traffic is monitored for abuse.",reviewedAt:"2026-09-24",models:GO.filter(row=>row[1]!=="unsupported").map(row=>row[0])}),modelProtocols:rows(GO),requestIdentity:identity},
 {...descriptor({id:"opencode-zen",name:"OpenCode Zen",vendor:"OpenCode",category:"api",transport:"openai-chat",billing:"payg",url:"https://opencode.ai/zen/v1",source:"https://opencode.ai/docs/zen/",summary:"Pay-as-you-go gateway for curated models. Some models are served over OpenAI Responses or Anthropic Messages; Gemini-native models are not supported by MathOS.",reviewedAt:"2026-09-24",models:ZEN.filter(row=>row[1]!=="unsupported").map(row=>row[0])}),modelProtocols:rows(ZEN),requestIdentity:identity},
]
