import type { ProviderDescriptor } from "./types.ts";import { descriptor } from "./presets-core.ts"
export const CN_PROVIDER_PRESETS:ProviderDescriptor[]=[
 descriptor({id:"minimax-token-plan-cn",name:"MiniMax Token Plan China",vendor:"MiniMax",category:"plan",transport:"anthropic-messages",billing:"subscription",url:"https://api.minimaxi.com/anthropic",source:"https://platform.minimaxi.com/docs",policy:"SCOPED_PLAN"}),
 descriptor({id:"alibaba-token-plan-personal",name:"Alibaba Token Plan Personal",vendor:"Alibaba Cloud",category:"plan",transport:"openai-chat",billing:"subscription",url:"https://coding-intl.dashscope.aliyuncs.com/v1",source:"https://www.alibabacloud.com/help/en/model-studio/token-plan-overview",policy:"REQUIRES_VENDOR_APPROVAL"}),
 descriptor({id:"alibaba-token-plan-team",name:"Alibaba Token Plan Team",vendor:"Alibaba Cloud",category:"plan",transport:"openai-chat",billing:"subscription",url:"https://coding-intl.dashscope.aliyuncs.com/v1",source:"https://www.alibabacloud.com/help/en/model-studio/token-plan-overview",policy:"REQUIRES_VENDOR_APPROVAL"}),
 descriptor({id:"alibaba-coding-plan",name:"Alibaba Coding Plan",vendor:"Alibaba Cloud",category:"plan",transport:"openai-chat",billing:"subscription",url:"https://coding-intl.dashscope.aliyuncs.com/v1",source:"https://www.alibabacloud.com/help/en/model-studio/more-tools",policy:"REQUIRES_VENDOR_APPROVAL"}),
 descriptor({id:"alibaba-model-studio-payg",name:"Alibaba Model Studio PAYG",vendor:"Alibaba Cloud",category:"api",transport:"openai-chat",billing:"payg",url:"https://dashscope-intl.aliyuncs.com/compatible-mode/v1",source:"https://www.alibabacloud.com/help/en/model-studio"}),
 descriptor({id:"qwen-code-acp",name:"Qwen Code ACP",vendor:"Alibaba/Qwen",category:"subscription",transport:"external-acp",billing:"unknown",source:"https://qwenlm.github.io/qwen-code-docs/en/developers/architecture/",policy:"OFFICIAL_CLIENT_BRIDGE",auth:["upstream-client"],client:{id:"qwen",executableNames:["qwen"],protocol:"acp",ownsCredentials:true}}),
 descriptor({id:"qwen-portal-oauth-legacy",name:"Qwen Portal OAuth Legacy",vendor:"Alibaba/Qwen",category:"subscription",transport:"external-acp",billing:"unknown",source:"https://qwenlm.github.io/qwen-code-docs/en/users/configuration/auth/",policy:"RETIRED",auth:["none"],discovery:{kind:"manual"}}),
]
const minimaxCn=CN_PROVIDER_PRESETS.find(item=>item.id==="minimax-token-plan-cn")!;minimaxCn.endpointPresets.push({id:"openai",baseUrl:"https://api.minimaxi.com/v1",protocol:"openai"});minimaxCn.defaultModels=["MiniMax-M2.7","MiniMax-M2.7-highspeed"]
