import type { ProviderDescriptor, ProviderTermsPolicy, ProviderTransportKind } from "./types.ts"
const platforms:ProviderDescriptor["supportedPlatforms"]=["win32-x64","darwin-arm64","darwin-x64","linux-x64","linux-arm64"]
type Input={id:string;name:string;vendor:string;category:ProviderDescriptor["category"];transport:ProviderTransportKind;billing:ProviderDescriptor["billingClass"];url?:string;source:string;policy?:ProviderTermsPolicy;auth?:ProviderDescriptor["authKinds"];client?:ProviderDescriptor["externalClient"];discovery?:ProviderDescriptor["modelDiscovery"]}
export const descriptor=(x:Input):ProviderDescriptor=>({id:x.id,displayName:x.name,vendor:x.vendor,category:x.category,transport:x.transport,authKinds:x.auth??["secret-ref"],billingClass:x.billing,remote:true,terms:{policy:x.policy??"STANDARD_API",summary:x.policy??"Standard provider API",officialSources:[x.source],lastReviewedAt:"2026-09-02",userOverrideAllowed:!["PROHIBITED_THIRD_PARTY","RETIRED","REQUIRES_VENDOR_APPROVAL","TERMS_REVIEW_REQUIRED"].includes(x.policy??"")},endpointPresets:x.url?[{id:"default",baseUrl:x.url,protocol:x.transport==="anthropic-messages"?"anthropic":x.transport.startsWith("external")?"external":"openai"}]:[],externalClient:x.client,modelDiscovery:x.discovery??(x.url?{kind:"openai-models",path:"/models"}:{kind:"external-client"}),defaultModels:[],truthfulClientIdentityRequired:true,supportedPlatforms:platforms})
export const CORE_PROVIDER_PRESETS:ProviderDescriptor[]=[
 descriptor({id:"openai-api",name:"OpenAI API",vendor:"OpenAI",category:"api",transport:"openai-responses",billing:"payg",url:"https://api.openai.com/v1",source:"https://platform.openai.com/docs"}),
 descriptor({id:"openai-codex-chatgpt",name:"ChatGPT/Codex",vendor:"OpenAI",category:"subscription",transport:"external-jsonrpc",billing:"subscription",source:"https://github.com/openai/codex/blob/main/codex-rs/app-server/README.md",policy:"OFFICIAL_CLIENT_BRIDGE",auth:["upstream-client"],client:{id:"codex",executableNames:["codex"],protocol:"jsonrpc",ownsCredentials:true}}),
 descriptor({id:"openrouter",name:"OpenRouter",vendor:"OpenRouter",category:"api",transport:"openai-chat",billing:"payg",url:"https://openrouter.ai/api/v1",source:"https://openrouter.ai/docs/api/api-reference/models/get-models"}),
 descriptor({id:"anthropic-api",name:"Anthropic API",vendor:"Anthropic",category:"api",transport:"anthropic-messages",billing:"payg",url:"https://api.anthropic.com/v1",source:"https://docs.anthropic.com"}),
 descriptor({id:"claude-code-account",name:"Claude Code Account",vendor:"Anthropic",category:"subscription",transport:"external-jsonrpc",billing:"subscription",source:"https://support.claude.com/en/articles/11145838-use-claude-code-with-your-pro-or-max-plan",policy:"REQUIRES_VENDOR_APPROVAL",auth:["upstream-client"],client:{id:"claude",executableNames:["claude"],protocol:"cli-json",ownsCredentials:true}}),
 descriptor({id:"github-copilot-account",name:"GitHub Copilot",vendor:"GitHub",category:"subscription",transport:"copilot-sdk",billing:"subscription",source:"https://docs.github.com/en/copilot/how-tos/copilot-sdk/auth/authenticate",policy:"OFFICIAL_CLIENT_BRIDGE",auth:["copilot-logged-in-user"],client:{id:"copilot",executableNames:[],protocol:"sdk",ownsCredentials:true},discovery:{kind:"sdk"}}),
 descriptor({id:"gemini-api",name:"Gemini API",vendor:"Google",category:"api",transport:"openai-chat",billing:"payg",url:"https://generativelanguage.googleapis.com/v1beta/openai",source:"https://ai.google.dev/gemini-api/docs/openai"}),
 descriptor({id:"google-vertex",name:"Vertex AI",vendor:"Google",category:"api",transport:"openai-chat",billing:"enterprise",source:"https://cloud.google.com/vertex-ai/generative-ai/docs",auth:["application-default"],discovery:{kind:"manual"}}),
 descriptor({id:"gemini-cli-enterprise",name:"Gemini CLI Enterprise (supported enterprise accounts; individual access changed after 2026-06-18)",vendor:"Google",category:"subscription",transport:"external-acp",billing:"enterprise",source:"https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/acp-mode.md",policy:"OFFICIAL_CLIENT_BRIDGE",auth:["upstream-client"],client:{id:"gemini",executableNames:["gemini"],protocol:"acp",ownsCredentials:true}}),
 descriptor({id:"google-antigravity-consumer",name:"Google Antigravity Consumer",vendor:"Google",category:"subscription",transport:"external-jsonrpc",billing:"subscription",source:"https://antigravity.google/terms",policy:"PROHIBITED_THIRD_PARTY",auth:["upstream-client"],discovery:{kind:"manual"}}),
 descriptor({id:"google-antigravity-enterprise-api",name:"Google Antigravity Enterprise API",vendor:"Google",category:"api",transport:"openai-responses",billing:"enterprise",source:"https://cloud.google.com",policy:"REQUIRES_VENDOR_APPROVAL",auth:["application-default"],discovery:{kind:"manual"}}),
 descriptor({id:"kimi-code-membership",name:"Kimi Code Membership",vendor:"Moonshot AI",category:"plan",transport:"openai-chat",billing:"subscription",url:"https://api.kimi.com/coding/v1",source:"https://www.kimi.com/code/docs/en/",policy:"SCOPED_PLAN"}),
 descriptor({id:"kimi-platform-payg",name:"Kimi Platform PAYG",vendor:"Moonshot AI",category:"api",transport:"openai-chat",billing:"payg",url:"https://api.moonshot.ai/v1",source:"https://platform.moonshot.ai/docs"}),
 descriptor({id:"minimax-token-plan-global",name:"MiniMax Token Plan Global",vendor:"MiniMax",category:"plan",transport:"anthropic-messages",billing:"subscription",url:"https://api.minimax.io/anthropic",source:"https://platform.minimax.io/docs/token-plan/other-tools",policy:"SCOPED_PLAN"}),
 descriptor({id:"minimax-payg",name:"MiniMax PAYG",vendor:"MiniMax",category:"api",transport:"openai-chat",billing:"payg",url:"https://api.minimax.io/v1",source:"https://platform.minimax.io/docs"}),
 descriptor({id:"zai-payg",name:"Z.AI PAYG",vendor:"Z.AI",category:"api",transport:"openai-chat",billing:"payg",url:"https://api.z.ai/api/paas/v4",source:"https://docs.z.ai/guides/develop/http/introduction"}),
 descriptor({id:"zai-coding-plan",name:"Z.AI Coding Plan",vendor:"Z.AI",category:"plan",transport:"openai-chat",billing:"subscription",url:"https://api.z.ai/api/coding/paas/v4",source:"https://docs.z.ai/devpack/faq",policy:"REQUIRES_VENDOR_APPROVAL"}),
 descriptor({id:"deepseek-api",name:"DeepSeek API",vendor:"DeepSeek",category:"api",transport:"openai-chat",billing:"payg",url:"https://api.deepseek.com/v1",source:"https://api-docs.deepseek.com/"}),
 descriptor({id:"generic-openai-compatible",name:"Generic OpenAI-compatible",vendor:"Generic",category:"generic",transport:"openai-chat",billing:"unknown",source:"https://platform.openai.com/docs/api-reference",discovery:{kind:"manual"}}),
 descriptor({id:"generic-anthropic-compatible",name:"Generic Anthropic-compatible",vendor:"Generic",category:"generic",transport:"anthropic-messages",billing:"unknown",source:"https://docs.anthropic.com/en/api/messages",discovery:{kind:"manual"}}),
]
const kimiCode=CORE_PROVIDER_PRESETS.find(item=>item.id==="kimi-code-membership")!;kimiCode.endpointPresets.push({id:"anthropic",baseUrl:"https://api.kimi.com/coding/v1",protocol:"anthropic"});kimiCode.defaultModels=["k3","k3-256k","kimi-for-coding","kimi-for-coding-highspeed"]
const kimiPayg=CORE_PROVIDER_PRESETS.find(item=>item.id==="kimi-platform-payg")!;kimiPayg.endpointPresets.push({id:"anthropic",baseUrl:"https://api.moonshot.ai/anthropic",protocol:"anthropic"})
const minimaxGlobal=CORE_PROVIDER_PRESETS.find(item=>item.id==="minimax-token-plan-global")!;minimaxGlobal.endpointPresets.push({id:"openai",baseUrl:"https://api.minimax.io/v1",protocol:"openai"});minimaxGlobal.defaultModels=["MiniMax-M2.7","MiniMax-M2.7-highspeed"]
const minimaxPayg=CORE_PROVIDER_PRESETS.find(item=>item.id==="minimax-payg")!;minimaxPayg.endpointPresets.push({id:"anthropic",baseUrl:"https://api.minimax.io/anthropic",protocol:"anthropic"});minimaxPayg.defaultModels=["MiniMax-M2.7","MiniMax-M2.7-highspeed","MiniMax-M2.5","MiniMax-M2.5-highspeed","MiniMax-M2.1","MiniMax-M2.1-highspeed","MiniMax-M2"]
const zaiPayg=CORE_PROVIDER_PRESETS.find(item=>item.id==="zai-payg")!;zaiPayg.endpointPresets.push({id:"anthropic",baseUrl:"https://api.z.ai/api/anthropic",protocol:"anthropic"});zaiPayg.defaultModels=["GLM-5.1","GLM-5-Turbo","GLM-4.7","GLM-4.5-Air"]
const zaiPlan=CORE_PROVIDER_PRESETS.find(item=>item.id==="zai-coding-plan")!;zaiPlan.endpointPresets.push({id:"anthropic",baseUrl:"https://api.z.ai/api/anthropic",protocol:"anthropic"});zaiPlan.defaultModels=["GLM-5.1","GLM-5-Turbo","GLM-4.7","GLM-4.5-Air"]
const deepseek=CORE_PROVIDER_PRESETS.find(item=>item.id==="deepseek-api")!;deepseek.defaultModels=["deepseek-v4-pro","deepseek-v4-flash"]
