import { For } from "solid-js"
import { theme } from "../theme.ts"
type Row = { id?: string; title?: string; status?: string; locator?: unknown; relation?: string }
export function literatureDeskSnapshot(input: { sources?: Row[]; excerpts?: Row[]; candidates?: Row[]; assessments?: Row[] }) { return { schemaVersion: "mathos.literature-desk.v1" as const, trustBanner: "EXTERNAL RESULTS — NOT A PROOF", sources: input.sources ?? [], excerpts: input.excerpts ?? [], candidates: input.candidates ?? [], assessments: input.assessments ?? [] } }
export function literatureDeskCommand(args: string[]): { action: "IMPORT_PLAN" | "IMPORT_APPLY" | "BIB_IMPORT" | "SEARCH" | "PAGES" | "REVIEW" | "ASSESS" | "DESK"; args: string[] } {
  const [family, verb] = args
  const action = family === "import" && verb === "plan" ? "IMPORT_PLAN" : family === "import" && verb === "apply" ? "IMPORT_APPLY" : family === "bib" && verb === "import" ? "BIB_IMPORT" : family === "search" ? "SEARCH" : family === "pages" ? "PAGES" : family === "review" ? "REVIEW" : family === "assess" ? "ASSESS" : "DESK"
  return { action, args: args.slice(action === "IMPORT_PLAN" || action === "IMPORT_APPLY" || action === "BIB_IMPORT" ? 2 : 1) }
}
export function LiteratureDeskView(props: { snapshot: ReturnType<typeof literatureDeskSnapshot> }) { return <box flexGrow={1} padding={1} flexDirection="column"><text fg={theme.accent}>LITERATURE DESK</text><text fg={theme.warning}>{props.snapshot.trustBanner}</text><text fg={theme.textMuted}>SOURCE LIBRARY</text><For each={props.snapshot.sources}>{row => <text fg={theme.text}>{`${row.id} ${row.title ?? row.status ?? ""}`}</text>}</For><text fg={theme.textMuted}>PAGES / EXCERPTS</text><For each={props.snapshot.excerpts}>{row => <text fg={theme.text}>{`${row.id} ${typeof row.locator === "string" ? row.locator : JSON.stringify(row.locator ?? "")}`}</text>}</For><text fg={theme.textMuted}>CANDIDATE QUEUE</text><For each={props.snapshot.candidates}>{row => <text fg={theme.text}>{`${row.id} ${row.status ?? ""}`}</text>}</For><text fg={theme.textMuted}>SUPPORT MATRIX</text><For each={props.snapshot.assessments}>{row => <text fg={theme.text}>{`${row.id} ${row.relation ?? row.status ?? ""}`}</text>}</For></box> }
/** @jsxImportSource @opentui/solid */
