#!/usr/bin/env bun
import { execFileSync } from "node:child_process"
import { homedir } from "node:os"
import { join, resolve } from "node:path"
import { createProviderFromProfile, createSecretStore, evaluateProviderPolicy, loadModelProfileStore, providerCatalog, type ModelProfileV2 } from "@mathos/models"
import { resolveRuntimeLayout } from "@mathos/shared"

export interface ProviderLiveResult { schemaVersion:"mathos.provider-live-smoke.v1";platform:string;mathosRevision:string;providerDescriptor:string;profile:string;clientVersion:string|null;transport:string;authOwner:string;model:string;connection:string;modelList:string;quota:string;liveRequest:string;usage:unknown;termsPolicy:string }
function revision(){try{return execFileSync("git",["rev-parse","HEAD"],{cwd:resolve(import.meta.dir,"../.."),encoding:"utf8"}).trim()}catch{return"UNKNOWN"}}
export async function runProviderLiveSmoke(argv:string[],options:{profiles?:ModelProfileV2[]}={}):Promise<ProviderLiveResult>{if(argv.some(value=>/^(--api-key|--token|--secret|--password|--value)(=|$)/i.test(value)))throw new Error("LIVE_SMOKE_SECRET_ARG_FORBIDDEN");const profileId=argv.find(value=>!value.startsWith("--"));if(!profileId)throw new Error("LIVE_SMOKE_PROFILE_REQUIRED");const layout=resolveRuntimeLayout({executablePath:process.execPath,platform:process.platform,home:homedir(),env:process.env}),profiles=options.profiles??loadModelProfileStore(join(layout.userConfigRoot,"model-profiles.json")).profiles,profile=profiles.find(row=>row.id===profileId);if(!profile)throw new Error(`MODEL_PROFILE_NOT_FOUND: ${profileId}`);const descriptor=providerCatalog.get(profile.descriptorId);if(!descriptor)throw new Error(`PROVIDER_DESCRIPTOR_NOT_FOUND: ${profile.descriptorId}`);const policy=evaluateProviderPolicy(descriptor.id),base={schemaVersion:"mathos.provider-live-smoke.v1" as const,platform:`${process.platform}-${process.arch}`,mathosRevision:revision(),providerDescriptor:descriptor.id,profile:profile.id,clientVersion:null,transport:descriptor.transport,authOwner:profile.auth.kind,model:profile.model,modelList:"NOT_RUN",quota:"NOT_RUN",usage:null,termsPolicy:descriptor.terms.policy};if(!policy.allowed)return{...base,connection:"POLICY_BLOCKED_EXPECTED",liveRequest:"POLICY_BLOCKED_EXPECTED"};const live=argv.includes("--live");if(!live)return{...base,connection:"NOT_CONFIGURED",liveRequest:"NOT_REQUESTED"};if(descriptor.billingClass==="payg"&&!argv.includes("--accept-usage"))throw new Error("LIVE_USAGE_ACCEPTANCE_REQUIRED");if(profile.model==="auto")return{...base,connection:"NOT_CONFIGURED",liveRequest:"MODEL_UNRESOLVED"};const secrets=createSecretStore();if(profile.auth.kind==="secret-ref"&&!await secrets.get(profile.auth.secretRef))return{...base,connection:"NOT_CONFIGURED",liveRequest:"NOT_CONFIGURED"};try{const provider=await createProviderFromProfile(profile,{secrets,live:true,acceptUsage:argv.includes("--accept-usage")});const response=await provider.generate({messages:[{role:"user",content:"Reply with OK only."}],maxOutputTokens:8});await (provider as {close?:()=>Promise<void>}).close?.();return{...base,connection:"CONNECTED",liveRequest:"PASS",usage:response.usage??null}}catch(error){return{...base,connection:"ERROR",liveRequest:error instanceof Error?error.message:"ERROR"}}
}
if(import.meta.main){runProviderLiveSmoke(process.argv.slice(2)).then(report=>process.stdout.write(`${JSON.stringify(report,null,2)}\n`)).catch(error=>{process.stderr.write(`${error instanceof Error?error.message:String(error)}\n`);process.exit(1)})}
